google.maps.__gjsload__('controls', function(_){var dta,wE,eta,xE,fta,gta,hta,ita,AE,kta,lta,mta,nta,BE,ota,qta,CE,DE,EE,rta,FE,GE,HE,uta,IE,JE,KE,vta,LE,yta,xta,wta,ME,OE,Ata,Bta,Cta,Dta,Eta,Fta,zta,PE,SE,Hta,Gta,TE,UE,Jta,Ita,Kta,Lta,Mta,WE,XE,Nta,Ota,Pta,YE,Sta,Rta,$E,bF,aF,Xta,Uta,Vta,Wta,cF,Yta,dF,Zta,eF,fF,aua,$ta,bua,cua,gF,iF,hF,kF,dua,fua,lF,gua,mF,hua,kua,iua,jua,nua,mua,lua,pua,nF,qua,oF,pF,rua,qF,uua,tua,sua,rF,vua,wua,xua,yua,sF,zua,Bua,Aua,tF,Cua,Eua,Dua,uF,wF,Fua,Gua,xF,Hua,zF,yF,AF,BF,CF,Iua,DF,EF,Jua,FF,Kua,Lua,Mua,GF,Pua,Qua,
Nua,HF,Sua,Rua,Tua,Uua,JF,IF,Vua,Wua,KF,fva,bva,hva,nva,MF,LF,ova,eva,gva,Zua,ava,pva,$ua,dva,iva,Yua,rva,sva,tva,uva,vva,NF,Xua,kva,mva,lva,jva,OF,cva,wva,xva,qva,yva,zva,PF,Ava,Bva,QF,Cva,Eva,Dva,RF,pta;dta=function(a,b,c){_.br(a,b,"animate",c)};wE=function(a){a.style.textAlign=_.gt.Wb()?"right":"left"};eta=function(a,b){b instanceof _.rb||b instanceof _.rb||(b="object"==typeof b&&b.yg?b.Ic():String(b),_.ema.test(b)||(b="about:invalid#zClosurez"),b=_.sb(b));a.href=_.vl(b)};
xE=function(a){return a?"none"!==a.style.display:!1};fta=function(a,b){switch(_.Kw(b)){case 1:"ltr"!==a.dir&&(a.dir="ltr");break;case -1:"rtl"!==a.dir&&(a.dir="rtl");break;default:a.removeAttribute("dir")}};gta=function(a,b,c){if(!a||!b||"number"!==typeof c)return null;c=Math.pow(2,-c);var d=a.fromLatLngToPoint(b);return _.Wu(a.fromPointToLatLng(new _.Q(d.x+c,d.y)),b)};hta=function(a,b,c){for(var d="string"===typeof a?a.split(""):a,e=a.length-1;0<=e;--e)e in d&&b.call(c,d[e],e,a)};
ita=function(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};_.yE=function(a,b){a.classList?a.classList.remove(b):_.Dga(a,b)&&_.Cga(a,Array.prototype.filter.call(a.classList?a.classList:_.rm(a).match(/\S+/g)||[],function(c){return c!=b}).join(" "))};_.zE=function(a){_.yE(a,"gmnoscreen");_.sm(a,"gmnoprint")};_.jta=function(a){_.Di.ld?a.style.styleFloat="left":a.style.cssFloat="left"};
AE=function(a,b){a.style.WebkitBorderRadius=b;a.style.borderRadius=b;a.style.MozBorderRadius=b};kta=function(a,b){a.style.WebkitBorderTopLeftRadius=b;a.style.WebkitBorderTopRightRadius=b;a.style.borderTopLeftRadius=b;a.style.borderTopRightRadius=b;a.style.MozBorderTopLeftRadius=b;a.style.MozBorderTopRightRadius=b};
lta=function(a,b){a.style.WebkitBorderBottomLeftRadius=b;a.style.WebkitBorderBottomRightRadius=b;a.style.borderBottomLeftRadius=b;a.style.borderBottomRightRadius=b;a.style.MozBorderBottomLeftRadius=b;a.style.MozBorderBottomRightRadius=b};mta=function(a){var b=_.Nl(2);a.style.WebkitBorderBottomLeftRadius=b;a.style.WebkitBorderTopLeftRadius=b;a.style.borderBottomLeftRadius=b;a.style.borderTopLeftRadius=b;a.style.MozBorderBottomLeftRadius=b;a.style.MozBorderTopLeftRadius=b};
nta=function(a){var b=_.Nl(2);a.style.WebkitBorderBottomRightRadius=b;a.style.WebkitBorderTopRightRadius=b;a.style.borderBottomRightRadius=b;a.style.borderTopRightRadius=b;a.style.MozBorderBottomRightRadius=b;a.style.MozBorderTopRightRadius=b};
BE=function(a,b){b=b||{};var c=a.style;c.color="black";c.fontFamily="Roboto,Arial,sans-serif";_.Om(a);_.Nm(a);b.title&&a.setAttribute("title",b.title);c=_.Qm()?1.38:1;a=a.style;a.fontSize=_.Nl(b.fontSize||11);a.backgroundColor="#fff";for(var d=[],e=0,f=_.Yd(b.padding);e<f;++e)d.push(_.Nl(c*b.padding[e]));a.padding=d.join(" ");b.width&&(a.width=_.Nl(c*b.width))};ota=function(){return _.Cfa.some(function(a){return!!document[a]})};
qta=function(a,b){var c=pta[b];if(!c){var d=ita(b);c=d;void 0===a.style[d]&&(d=_.Lw()+_.kma(d),void 0!==a.style[d]&&(c=d));pta[b]=c}return c};CE=function(a,b,c){if("string"===typeof b)(b=qta(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=qta(c,d);f&&(c.style[f]=e)}};DE=function(a,b,c){if(b instanceof _.Ol){var d=b.x;b=b.y}else d=b,b=c;a.style.left=_.Mw(d,!1);a.style.top=_.Mw(b,!1)};EE=function(a){return 40<a?a/2-2:28>a?a-10:18};
rta=function(a,b){a.items=a.items||[];var c=a.items[b]=a.items[b]||{},d=_.Wra(a,b);if(!c.ee){a.j=a.j||new _.Q(0,0);var e=a.items[0]&&a.items[0].ee||new _.Q(0,0);c.ee=new _.Q(e.x+a.j.x*b,e.y+a.j.y*b)}return{url:d,size:c.Uc||a.Uc,scaledSize:a.h.size,origin:c.ee,anchor:c.anchor||a.anchor}};
_.tta=function(a,b){var c=document.createElement("div"),d=c.style;d.backgroundColor="white";d.fontWeight="500";d.fontFamily="Roboto, sans-serif";d.padding="15px 25px";d.boxSizing="border-box";d.top="5px";d=document.createElement("div");var e=document.createElement("img");e.alt="";e.src=_.Rs+"api-3/images/google_gray.svg";e.style.border=e.style.margin=e.style.padding=0;e.style.height="17px";e.style.verticalAlign="middle";e.style.width="52px";_.Nm(e);d.appendChild(e);c.appendChild(d);d=document.createElement("div");
d.style.lineHeight="20px";d.style.margin="15px 0";e=document.createElement("span");e.style.color="rgba(0,0,0,0.87)";e.style.fontSize="14px";e.innerText="\u041d\u0435 \u0432\u0434\u0430\u0454\u0442\u044c\u0441\u044f \u0437\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0438\u0442\u0438 \u041a\u0430\u0440\u0442\u0438 Google \u043d\u0430 \u0446\u0456\u0439 \u0441\u0442\u043e\u0440\u0456\u043d\u0446\u0456.";d.appendChild(e);c.appendChild(d);d=document.createElement("table");d.style.width="100%";e=document.createElement("tr");
var f=document.createElement("td");f.style.lineHeight="16px";f.style.verticalAlign="middle";var g=document.createElement("a");eta(g,b);g.innerText="\u0412\u0438 \u0454 \u0432\u043b\u0430\u0441\u043d\u0438\u043a\u043e\u043c \u0446\u044c\u043e\u0433\u043e \u0432\u0435\u0431-\u0441\u0430\u0439\u0442\u0443?";g.target="_blank";g.setAttribute("rel","noopener");g.style.color="rgba(0, 0, 0, 0.54)";g.style.fontSize="12px";g.onclick=function(){_.P(a,"Dl");_.rg(a,148243)};f.appendChild(g);e.appendChild(f);_.Zm(sta);
b=document.createElement("td");b.style.textAlign="right";f=document.createElement("button");f.className="dismissButton";f.innerText="\u041e\u041a";f.onclick=function(){a.removeChild(c);_.M(a,"dmd");_.P(a,"Dd");_.rg(a,148242)};b.appendChild(f);e.appendChild(b);d.appendChild(e);c.appendChild(d);a.appendChild(c);_.P(a,"D0");_.rg(a,148244);return c};
FE=function(a){var b=this;this.j=a;this.Fa=new _.ni(function(){return b.m()},0);_.Ql(a,"resize",this,this.m);this.h=new _.x.Map;this.C=new _.x.Map;a=_.A([1,2,3,5,7,4,13,8,6,9,10,11,12]);for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=document.createElement("div");this.j.appendChild(d);this.C.set(c,d);this.h.set(c,[])}};
GE=function(a,b){if(!xE(a))return 0;b=!b&&_.Uu(a.dataset.controlWidth);if(!_.he(b)||isNaN(b))b=a.offsetWidth;a=_.Qw(a);b+=_.Uu(a.marginLeft)||0;return b+=_.Uu(a.marginRight)||0};HE=function(a,b){if(!xE(a))return 0;b=!b&&_.Uu(a.dataset.controlHeight);if(!_.he(b)||isNaN(b))b=a.offsetHeight;a=_.Qw(a);b+=_.Uu(a.marginTop)||0;return b+=_.Uu(a.marginBottom)||0};
uta=function(a){for(var b=0,c=_.A(a),d=c.next();!d.done;d=c.next())b=Math.max(d.value.height,b);d=c=0;for(var e=a.length;0<e;--e){var f=a[e-1];if(b===f.height){f.width>d&&f.width>f.height?d=f.height:c=f.width;break}else d=Math.max(f.height,d)}return new _.Eg(c,d)};
IE=function(a,b,c,d){var e=0,f=0,g=[];a=_.A(a);for(var h=a.next();!h.done;h=a.next()){var k=h.value;h=k.border;k=k.element;var l=GE(k);var m=GE(k,!0),p=HE(k),q=HE(k,!0);k.style[b]=_.Nl("left"===b?e:e+(l-m));k.style[c]=_.Nl("top"===c?0:p-q);l=e+l;p>f&&(f=p,d.push({minWidth:e,height:f}));e=l;h||g.push(new _.Eg(e,p));k.style.visibility=""}return uta(g)};
JE=function(a,b,c,d){var e=0,f=[];a=_.A(a);for(var g=a.next();!g.done;g=a.next()){var h=g.value;g=h.border;h=h.element;for(var k=GE(h),l=HE(h),m=GE(h,!0),p=HE(h,!0),q=0,r=_.A(d),t=r.next();!t.done;t=r.next()){t=t.value;if(t.minWidth>k)break;q=t.height}e=Math.max(q,e);h.style[c]=_.Nl("top"===c?e:e+l-p);h.style[b]=_.Nl("left"===b?0:k-m);e+=l;g||f.push(new _.Eg(k,e));h.style.visibility=""}return uta(f)};
KE=function(a,b,c,d){for(var e=0,f=0,g=_.A(a),h=g.next();!h.done;h=g.next()){var k=h.value;h=k.border;k=k.element;var l=GE(k),m=HE(k),p=GE(k,!0);"left"===b?k.style.left="0":"right"===b?k.style.right=_.Nl(l-p):k.style.left=_.Nl((c-p)/2);e+=m;h||(f=Math.max(l,f))}b=(d-e)/2;a=_.A(a);for(c=a.next();!c.done;c=a.next())c=c.value.element,c.style.top=_.Nl(b),b+=HE(c),c.style.visibility="";return f};
vta=function(a,b,c){for(var d=0,e=0,f=_.A(a),g=f.next();!g.done;g=f.next()){var h=g.value;g=h.border;h=h.element;var k=GE(h),l=HE(h),m=HE(h,!0);h.style[b]=_.Nl("top"===b?0:l-m);d+=k;g||(e=Math.max(l,e))}b=(c-d)/2;a=_.A(a);for(c=a.next();!c.done;c=a.next())c=c.value.element,c.style.left=_.Nl(b),b+=GE(c),c.style.visibility="";return e};LE=function(a,b,c,d,e,f,g){this.label=a||"";this.alt=b||"";this.C=f||null;this.vf=c;this.h=d;this.m=e;this.j=g||null};
yta=function(a,b){var c=this;this.F=a;b=b||["roadmap","satellite","hybrid","terrain"];var d=_.lb(b,"terrain")&&_.lb(b,"roadmap"),e=_.lb(b,"hybrid")&&_.lb(b,"satellite");this.m={};this.C=[];this.j=this.D=this.h=null;_.L(this,"maptypeid_changed",function(){var k=c.get("mapTypeId");c.j&&c.j.set("display","satellite"==k);c.h&&c.h.set("display","roadmap"==k)});_.L(this,"zoom_changed",function(){if(c.h){var k=c.get("zoom");c.h.set("enabled",k<=c.D)}});b=_.A(b);for(var f=b.next();!f.done;f=b.next())if(f=
f.value,"hybrid"!=f||!e)if("terrain"!=f||!d){var g=a.get(f);if(g){var h=null;"roadmap"==f?d&&(this.h=wta(this,"terrain","roadmap","terrain",void 0,"\u0417\u043c\u0435\u043d\u0448\u0438\u0442\u0438 \u043c\u0430\u0441\u0448\u0442\u0430\u0431, \u0449\u043e\u0431 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u043d\u0443\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u0432\u0443\u043b\u0438\u0446\u044c \u0456\u0437 \u043b\u0430\u043d\u0434\u0448\u0430\u0444\u0442\u043e\u043c"),h=[[this.h]],this.D=a.get("terrain").maxZoom):
"satellite"!=f&&"hybrid"!=f||!e||(this.j=xta(this),h=[[this.j]]);this.C.push(new LE(g.name,g.alt,"mapTypeId",f,null,null,h))}}};xta=function(a){a=wta(a,"hybrid","satellite","labels","\u041c\u0456\u0442\u043a\u0438");a.set("enabled",!0);return a};wta=function(a,b,c,d,e,f){var g=a.F.get(b);e=new LE(e||g.name,g.alt,d,!0,!1,f);a.m[b]={mapTypeId:c,Ck:d,value:!0};a.m[c]={mapTypeId:c,Ck:d,value:!1};return e};ME=function(a){this.j=a;this.h=null};
OE=function(a){_.yz.call(this,a,NE);_.Qy(a,NE)||_.Py(a,NE,{options:0},["div",,1,0,[" ",["img",8,1,1]," ",["button",,1,2,[" ",["img",8,1,3]," ",["img",8,1,4]," ",["img",8,1,5]," "]]," ",["button",,1,6,[" ",["img",8,1,7]," ",["img",8,1,8]," ",["img",8,1,9]," "]]," ",["button",,1,10,[" ",["img",8,1,11]," ",["img",8,1,12]," ",["img",8,1,13]," "]]," <div> ",["div",,,14,["\u041f\u043e\u0432\u0435\u0440\u043d\u0443\u0442\u0438 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f"]]," ",["div",,,
15]," ",["div",,,16]," </div> "]],[],zta())};Ata=function(a){return _.W(a.options,"",-10)};Bta=function(a){return _.W(a.options,"",-7,-3)};Cta=function(a){return _.W(a.options,"",-8,-3)};Dta=function(a){return _.W(a.options,"",-9,-3)};Eta=function(a){return _.W(a.options,"",-12)};Fta=function(a){return _.W(a.options,"",-11)};
zta=function(){return[["$t","t-avKK8hDgg9Q","$a",[7,,,,,"gm-compass"]],["$a",[8,,,,function(a){return _.W(a.options,"",-3,-3)},"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"48","width",,1]],["$a",[7,,,,,"gm-control-active",,1],"$a",[7,,,,,"gm-compass-turn",,1],"$a",[0,,,,Ata,"aria-label",,,1],"$a",[0,,,,Ata,"title",,,1],"$a",[0,,,,"button","type",,1],"$a",[22,,,,function(){return"compass.counterclockwise"},"jsaction",,1]],["$a",[8,,,,Bta,"src",,,1],"$a",[0,,,,"","alt",
,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"14","width",,1]],["$a",[8,,,,Cta,"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"14","width",,1]],["$a",[8,,,,Dta,"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"14","width",,1]],["$a",[7,,,,,"gm-control-active",,1],"$a",[7,,,,,"gm-compass-needle",,1],"$a",[0,,,,Eta,"aria-label",,,1],"$a",[5,5,
,,function(a){return a.zb?_.dy("-webkit-transform","rotate("+String(_.W(a.options,0,-1))+"deg)"):"rotate("+String(_.W(a.options,0,-1))+"deg)"},"-webkit-transform",,,1],"$a",[5,5,,,function(a){return a.zb?_.dy("-ms-transform","rotate("+String(_.W(a.options,0,-1))+"deg)"):"rotate("+String(_.W(a.options,0,-1))+"deg)"},"-ms-transform",,,1],"$a",[5,5,,,function(a){return a.zb?_.dy("-moz-transform","rotate("+String(_.W(a.options,0,-1))+"deg)"):"rotate("+String(_.W(a.options,0,-1))+"deg)"},"-moz-transform",
,,1],"$a",[5,5,,,function(a){return a.zb?_.dy("transform","rotate("+String(_.W(a.options,0,-1))+"deg)"):"rotate("+String(_.W(a.options,0,-1))+"deg)"},"transform",,,1],"$a",[0,,,,Eta,"title",,,1],"$a",[0,,,,"button","type",,1],"$a",[22,,,,function(){return"compass.north"},"jsaction",,1]],["$a",[8,,,,function(a){return _.W(a.options,"",-4,-3)},"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"20","width",,1]],["$a",[8,,,,function(a){return _.W(a.options,
"",-5,-3)},"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"20","width",,1]],["$a",[8,,,,function(a){return _.W(a.options,"",-6,-3)},"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"20","width",,1]],["$a",[7,,,,,"gm-control-active",,1],"$a",[7,,,,,"gm-compass-turn",,1],"$a",[7,,,,,"gm-compass-turn-opposite",,1],"$a",[0,,,,Fta,"aria-label",,,1],"$a",[0,,,,Fta,"title",,,1],"$a",
[0,,,,"button","type",,1],"$a",[22,,,,function(){return"compass.clockwise"},"jsaction",,1]],["$a",[8,,,,Bta,"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"14","width",,1]],["$a",[8,,,,Cta,"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,,,,"14","width",,1]],["$a",[8,,,,Dta,"src",,,1],"$a",[0,,,,"","alt",,1],"$a",[0,,,,"false","draggable",,1],"$a",[0,,,,"48","height",,1],"$a",[0,
,,,"14","width",,1]],["$a",[7,,,,,"gm-compass-tooltip-text",,1]],["$a",[7,,,,,"gm-compass-arrow-right",,1],"$a",[7,,,,,"gm-compass-arrow-right-outer",,1]],["$a",[7,,,,,"gm-compass-arrow-right",,1],"$a",[7,,,,,"gm-compass-arrow-right-inner",,1]]]};PE=function(a){_.E.call(this,a)};SE=function(a){a=_.Ka(a);delete QE[a];_.cb(QE)&&RE&&RE.stop()};Hta=function(){RE||(RE=new _.ni(function(){Gta()},20));var a=RE;a.isActive()||a.start()};
Gta=function(){var a=_.Ma();_.pl(QE,function(b){Ita(b,a)});_.cb(QE)||Hta()};TE=function(){_.hi.call(this);this.h=0;this.endTime=this.startTime=null};UE=function(a,b,c,d){TE.call(this);if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.C=a;this.F=b;this.duration=c;this.D=d;this.coords=[];this.progress=0};
Jta=function(a){if(0==a.h)a.progress=0,a.coords=a.C;else if(1==a.h)return;SE(a);var b=_.Ma();a.startTime=b;-1==a.h&&(a.startTime-=a.duration*a.progress);a.endTime=a.startTime+a.duration;a.progress||a.j("begin");a.j("play");-1==a.h&&a.j("resume");a.h=1;var c=_.Ka(a);c in QE||(QE[c]=a);Hta();Ita(a,b)};
Ita=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);Kta(a,a.progress);1==a.progress?(a.h=0,SE(a),a.j("finish"),a.j("end")):1==a.h&&a.j("animate")};Kta=function(a,b){"function"===typeof a.D&&(b=a.D(b));a.coords=Array(a.C.length);for(var c=0;c<a.C.length;c++)a.coords[c]=(a.F[c]-a.C[c])*b+a.C[c]};
Lta=function(a,b){_.Oh.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.h};Mta=function(a){return 3*a*a-2*a*a*a};
WE=function(a,b,c){var d=this;this.j=a;b/=40;a.Aa.style.transform="scale("+b+")";a.Aa.style.transformOrigin="left";a.Aa.dataset.controlWidth=String(Math.round(48*b));a.Aa.dataset.controlHeight=String(Math.round(48*b));a.addListener("compass.clockwise","click",function(){return Nta(d,!0)});a.addListener("compass.counterclockwise","click",function(){return Nta(d,!1)});a.addListener("compass.north","click",function(){var e=d.get("pov");if(e){var f=_.Jl(e.heading,360);Ota(d,f,180>f?0:360,e.pitch,0)}});
this.h=null;this.m=!1;_.$m(VE,c)};XE=function(a){var b=a.get("mapSize"),c=a.get("panControl"),d=!!a.get("disableDefaultUI");a.j.Aa.style.visibility=c||void 0===c&&!d&&b&&200<=b.width&&200<=b.height?"":"hidden";_.M(a.j.Aa,"resize")};Nta=function(a,b){var c=a.get("pov");if(c){var d=_.Jl(c.heading,360);Ota(a,d,b?90*Math.floor((d+100)/90):90*Math.ceil((d-100)/90),c.pitch,c.pitch)}};
Ota=function(a,b,c,d,e){var f=new _.ar;a.h&&a.h.stop();b=a.h=new UE([b,d],[c,e],1200,Mta);dta(f,b,function(g){return Pta(a,!1,g)});_.Xla(f,b,"finish",function(g){return Pta(a,!0,g)});Jta(b)};Pta=function(a,b,c){a.m=!0;var d=a.get("pov");d&&(a.set("pov",{heading:c.coords[0],pitch:c.coords[1],zoom:d.zoom}),a.m=!1,b&&(a.h=null))};
YE=function(a,b,c,d){a.innerText="";b=_.A(b?1==c?[_.Zq["fullscreen_exit_normal_dark.svg"],_.Zq["fullscreen_exit_hover_dark.svg"],_.Zq["fullscreen_exit_active_dark.svg"]]:[_.Zq["fullscreen_exit_normal.svg"],_.Zq["fullscreen_exit_hover.svg"],_.Zq["fullscreen_exit_active.svg"]]:1==c?[_.Zq["fullscreen_enter_normal_dark.svg"],_.Zq["fullscreen_enter_hover_dark.svg"],_.Zq["fullscreen_enter_active_dark.svg"]]:[_.Zq["fullscreen_enter_normal.svg"],_.Zq["fullscreen_enter_hover.svg"],_.Zq["fullscreen_enter_active.svg"]]);
for(c=b.next();!c.done;c=b.next()){c=c.value;var e=document.createElement("img");e.style.width=e.style.height=_.Nl(EE(d));e.src=c;e.alt="";a.appendChild(e)}};
Sta=function(a,b,c,d){var e=this;this.m=a;this.C=d;this.h=b;this.h.style.cursor="pointer";this.h.setAttribute("aria-pressed",!1);this.Ed=c;this.j=ota();this.D=[];this.F=function(){e.Ed.set(_.lda(e.m))};this.refresh=function(){var f=e.get("display"),g=!!e.get("disableDefaultUI");_.mw(e.h,(void 0===f&&!g||!!f)&&e.j);_.M(e.h,"resize")};this.j&&(_.$m(VE,a),this.h.setAttribute("class","gm-control-active gm-fullscreen-control"),AE(this.h,_.Nl(_.Ez(d))),this.h.style.width=this.h.style.height=_.Nl(d),_.rw(this.h,
"0 1px 4px -1px rgba(0,0,0,0.3)"),a=this.get("controlStyle")||0,YE(this.h,this.Ed.get(),a,d),this.h.style.overflow="hidden",_.yf(this.h,"click",function(){if(e.Ed.get()){for(var f=_.A(_.Afa),g=f.next();!g.done;g=f.next())if(g=g.value,g in document){document[g]();break}e.h.setAttribute("aria-pressed",!1)}else{f=_.A(_.Bfa);for(g=f.next();!g.done;g=f.next())e.D.push(_.yf(document,g.value,e.F));f=e.m;g=_.A(_.Dfa);for(var h=g.next();!h.done;h=g.next())if(h=h.value,h in f){f[h]();break}e.h.setAttribute("aria-pressed",
!0)}}));_.L(this,"disabledefaultui_changed",this.refresh);_.L(this,"display_changed",this.refresh);_.L(this,"maptypeid_changed",function(){var f="streetview"==e.get("mapTypeId")?1:0;e.set("controlStyle",f);e.h.style.margin=_.Nl(e.C>>2);e.refresh()});_.L(this,"controlstyle_changed",function(){var f=e.get("controlStyle");null!=f&&(e.h.style.backgroundColor=Qta[f].backgroundColor,e.j&&YE(e.h,e.Ed.get(),f,e.C))});this.Ed.addListener(function(){_.M(e.m,"resize");e.Ed.get()||Rta(e);if(e.j){var f=e.get("controlStyle")||
0;YE(e.h,e.Ed.get(),f,e.C)}});this.refresh()};Rta=function(a){for(var b=_.A(a.D),c=b.next();!c.done;c=b.next())_.tf(c.value);a.D.length=0};
_.ZE=function(a,b){b=void 0===b?document.head:b;_.Om(a);_.Nm(a);_.$m(Tta,b);_.sm(a,"gm-style-cc");a.style.position="relative";b=_.Lm("div",a);_.Lm("div",b).style.width=_.Nl(1);var c=a.C=_.Lm("div",b);c.style.backgroundColor="#f5f5f5";c.style.width="auto";c.style.height="100%";c.style.marginLeft=_.Nl(1);_.pw(b,.7);b.style.width="100%";b.style.height="100%";_.Jm(b);b=a.m=_.Lm("div",a);b.style.position="relative";b.style.paddingLeft=b.style.paddingRight=_.Nl(6);b.style.boxSizing="border-box";b.style.fontFamily=
"Roboto,Arial,sans-serif";b.style.fontSize=_.Nl(10);b.style.color="#000000";b.style.whiteSpace="nowrap";b.style.direction="ltr";b.style.textAlign="right";a.style.height=_.Nl(14);a.style.lineHeight=_.Nl(14);b.style.verticalAlign="middle";b.style.display="inline-block";return b};$E=function(a){a.C&&(a.C.style.backgroundColor="#000",a.m.style.color="#fff")};
bF=function(a,b,c){_.zE(a);_.Mm(a,1000001);this.Ta=a;this.m=c;this.j=_.Lm("div",a);this.C=_.ZE(this.j,b);2===c&&$E(this.j);a=_.Yq("\u041a\u043e\u043c\u0431\u0456\u043d\u0430\u0446\u0456\u0457 \u043a\u043b\u0430\u0432\u0456\u0448");this.C.appendChild(a);a.textContent="\u041a\u043e\u043c\u0431\u0456\u043d\u0430\u0446\u0456\u0457 \u043a\u043b\u0430\u0432\u0456\u0448";a.style.color=1===this.m?"#000000":"#fff";a.style.display="inline-block";a.style.fontFamily="inherit";a.style.lineHeight="inherit";_.kw(a,
"click",this);this.h=a;a=new Image;a.src=1===this.m?_.Zq["keyboard_icon.svg"]:_.Zq["keyboard_icon_dark.svg"];a.alt="";a.style.height="10px";a.style.width="16px";a.style.verticalAlign="middle";this.D=a;aF(this)};aF=function(a){_.Ca(function(b){_.M(a.Ta,"resize");b.h=0})};
Xta=function(a,b){var c=this;this.h=document.activeElement===this.element;this.j=a;this.m=b;this.Ta=_.Lm("div");this.element=Uta(this);Vta(this);_.yf(this.element,"focus",function(){c.h=!0;Wta(c)});_.yf(this.element,"blur",function(){c.h=!1;Vta(c)});_.L(this,"update",function(){c.h&&Wta(c)});_.Cf(a,"update",this)};
Uta=function(a){var b=_.Yq("\u041a\u043e\u043c\u0431\u0456\u043d\u0430\u0446\u0456\u0457 \u043a\u043b\u0430\u0432\u0456\u0448");a.Ta.appendChild(b);_.Mm(b,1000002);b.style.position="absolute";b.style.backgroundColor="transparent";b.style.border="none";b.style.outlineOffset="3px";_.kw(b,"click",a.j.h);return b};Vta=function(a){a.element.style.right="0px";a.element.style.bottom="0px";a.element.style.transform="translateX(100%)"};
Wta=function(a){var b=a.j.h.getBoundingClientRect(),c=b.height,d=b.width,e=b.bottom;b=b.right;var f=a.m.getBoundingClientRect(),g=f.bottom;f=f.right;a.element.style.transform="";a.element.style.height=c+"px";a.element.style.width=d+"px";a.element.style.bottom=g-e+"px";a.element.style.right=f-b+"px"};cF=function(a,b,c){this.h=a;this.j=[];this.C=void 0===c?0:c;this.D=(this.m=3===b||12===b||6===b||9===b)?hta.bind(this):_.ib.bind(this);a.dataset.controlWidth="0";a.dataset.controlHeight="0"};
Yta=function(a,b){var c={element:b,height:0,width:0,Oo:_.L(b,"resize",function(){return dF(a,c)})};return c};
dF=function(a,b){b.width=_.Uu(b.element.dataset.controlWidth);b.height=_.Uu(b.element.dataset.controlHeight);b.width||(b.width=b.element.offsetWidth);b.height||(b.height=b.element.offsetHeight);var c=0;b=_.A(a.j);for(var d=b.next();!d.done;d=b.next()){var e=d.value;d=e.element;e=e.width;xE(d)&&"hidden"!==d.style.visibility&&(c=Math.max(c,e))}var f=0,g=!1,h=a.C;a.D(a.j,function(k){var l=k.element,m=k.height;k=k.width;xE(l)&&"hidden"!==l.style.visibility&&(g?f+=h:g=!0,l.style.left=_.Nl((c-k)/2),l.style.top=
_.Nl(f),f+=m)});b=c;d=f;a.h.dataset.controlWidth=b;a.h.dataset.controlHeight=d;_.mw(a.h,b||d);_.M(a.h,"resize")};
Zta=function(a,b){var c="\u0412\u0430\u0448 \u0432\u0435\u0431-\u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0430\u0447 \u043d\u0435 \u043f\u0456\u0434\u0442\u0440\u0438\u043c\u0443\u0454 Google Maps JavaScript API. \u0421\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0456\u043d\u0448\u0438\u0439 \u0432\u0435\u0431-\u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0430\u0447.",d=document.createElement("div");d.className="infomsg";a.appendChild(d);var e=d.style;e.background="#F9EDBE";e.border=
"1px solid #F0C36D";e.borderRadius="2px";e.boxSizing="border-box";e.boxShadow="0 2px 4px rgba(0,0,0,0.2)";e.fontFamily="Roboto,Arial,sans-serif";e.fontSize="12px";e.fontWeight="400";e.left="10%";e.h="2px";e.padding="5px 14px";e.position="absolute";e.textAlign="center";e.top="10px";e.webkitBorderRadius="2px";e.width="80%";e.zIndex=24601;d.innerText=c;c=document.createElement("a");b&&(d.appendChild(document.createTextNode(" ")),d.appendChild(c),c.innerText="\u0414\u043e\u043a\u043b\u0430\u0434\u043d\u0456\u0448\u0435",
c.href=b,c.target="_blank");b=document.createElement("a");d.appendChild(document.createTextNode(" "));d.appendChild(b);b.innerText="\u0417\u0430\u043a\u0440\u0438\u0442\u0438";b.target="_blank";c.style.paddingLeft=b.style.paddingLeft="0.8em";c.style.boxSizing=b.style.boxSizing="border-box";c.style.color=b.style.color="black";c.style.cursor=b.style.cursor="pointer";c.style.textDecoration=b.style.textDecoration="underline";c.style.whiteSpace=b.style.whiteSpace="nowrap";b.onclick=function(){a.removeChild(d)}};
eF=function(a){this.h=a.replace("www.google","maps.google")};
fF=function(a,b,c){var d=this;this.D=a;this.F=c;this.m=_.Lm("div");this.m.style.margin="0 5px";this.m.style.zIndex=1E6;this.h=_.Lm("a");this.h.style.display="inline";this.h.target="_blank";this.h.rel="noopener";this.h.title="\u0412\u0456\u0434\u043a\u0440\u0438\u0442\u0438 \u0446\u044e \u043e\u0431\u043b\u0430\u0441\u0442\u044c \u043d\u0430 \u041a\u0430\u0440\u0442\u0430\u0445 Google (\u0432\u0456\u0434\u043a\u0440\u0438\u0454\u0442\u044c\u0441\u044f \u043d\u043e\u0432\u0435 \u0432\u0456\u043a\u043d\u043e)";this.h.setAttribute("aria-label",
"\u0412\u0456\u0434\u043a\u0440\u0438\u0442\u0438 \u0446\u044e \u043e\u0431\u043b\u0430\u0441\u0442\u044c \u043d\u0430 \u041a\u0430\u0440\u0442\u0430\u0445 Google (\u0432\u0456\u0434\u043a\u0440\u0438\u0454\u0442\u044c\u0441\u044f \u043d\u043e\u0432\u0435 \u0432\u0456\u043a\u043d\u043e)");_.yl(this.h,_.jv(b.get("url")));this.h.addEventListener("click",function(){});this.C=_.Lm("div");a=new _.Eg(66,26);_.Ei(this.C,a);_.Om(this.C);this.j=_.cD(null,this.C,_.ch,a);this.j.alt="Google";_.L(b,"url_changed",
function(){_.yl(d.h,_.jv(b.get("url")))});_.L(this.D,"passivelogo_changed",function(){return $ta(d)});$ta(this)};aua=function(a,b){_.dD(a.j,b?_.Zq["google_logo_white.svg"]:_.Zq["google_logo_color.svg"])};$ta=function(a){a.F&&a.D.get("passiveLogo")?a.m.contains(a.h)?a.m.replaceChild(a.C,a.h):a.m.appendChild(a.C):(a.h.appendChild(a.C),a.m.appendChild(a.h))};
bua=function(a,b,c){function d(){var g=f.get("hasCustomStyles"),h=a.getMapTypeId();aua(e,g||"satellite"===h||"hybrid"===h)}var e=new fF(a,b,c),f=a.__gm;_.L(f,"hascustomstyles_changed",d);_.L(a,"maptypeid_changed",d);d();return e};
cua=function(a,b,c,d){function e(){0!=f.get("enabled")&&(null!=d&&f.get("active")?f.set("value",d):f.set("value",c))}var f=this;_.L(this,"value_changed",function(){f.set("active",f.get("value")==c)});new _.Eh(a,b,e);"click"==b&&"button"!=a.tagName.toLowerCase()&&new _.Eh(a,"keydown",function(g){"Enter"!=g.key&&" "!=g.key||e()});_.L(this,"display_changed",function(){_.mw(a,0!=f.get("display"))})};gF=function(a,b,c,d){return new cua(a,b,c,d)};
iF=function(a,b,c,d,e){var f=this;this.h=_.Yq(d.title);if(this.C=d.Rr||!1)this.h.setAttribute("role","menuitemradio"),this.h.setAttribute("aria-checked",!1);_.Hh(this.h);a.appendChild(this.h);_.$u(this.h);this.j=this.h.style;this.j.overflow="hidden";d.ko?wE(this.h):this.j.textAlign="center";d.height&&(this.j.height=_.Nl(d.height),this.j.display="table-cell",this.j.verticalAlign="middle");this.j.position="relative";BE(this.h,d);d.km&&mta(this.h);d.Po&&nta(this.h);this.h.style.webkitBackgroundClip=
"padding-box";this.h.style.backgroundClip="padding-box";this.h.style.MozBackgroundClip="padding";this.D=d.Yp||!1;this.F=d.km||!1;_.rw(this.h,"0 1px 4px -1px rgba(0,0,0,0.3)");d.gx?(a=document.createElement("span"),a.style.position="relative",_.Km(a,new _.Q(3,0),!_.gt.Wb(),!0),a.appendChild(b),this.h.appendChild(a),b=_.cD(_.gn("arrow-down"),this.h),_.Km(b,new _.Q(8,0),!_.gt.Wb()),b.style.top="50%",b.style.marginTop=_.Nl(-2),this.set("active",!1),this.h.setAttribute("aria-haspopup","true"),this.h.setAttribute("aria-expanded",
"false")):(this.h.appendChild(b),b=e(this.h,"click",c),b.bindTo("value",this),this.bindTo("active",b),b.bindTo("enabled",this));d.Mw&&this.h.setAttribute("aria-haspopup","true");d.Yp&&(this.j.fontWeight="500");this.m=_.Uu(this.j.paddingLeft)||0;d.ko||(this.j.fontWeight="500",d=this.h.offsetWidth-this.m-(_.Uu(this.j.paddingRight)||0),this.j.fontWeight="",_.he(d)&&0<=d&&(this.j.minWidth=_.Nl(d)));new _.Eh(this.h,"click",function(g){!1!==f.get("enabled")&&_.M(f,"click",g)});new _.Eh(this.h,"keydown",
function(g){!1!==f.get("enabled")&&_.M(f,"keydown",g)});new _.Eh(this.h,"blur",function(g){!1!==f.get("enabled")&&_.M(f,"blur",g)});new _.Eh(this.h,"mouseover",function(){return hF(f,!0)});new _.Eh(this.h,"mouseout",function(){return hF(f,!1)});_.L(this,"enabled_changed",function(){return hF(f,!1)});_.L(this,"active_changed",function(){return hF(f,!1)})};
hF=function(a,b){var c=!!a.get("active")||a.D;0==a.get("enabled")?(a.j.color="gray",b=c=!1):(a.j.color=c||b?"#000":"#565656",a.C&&a.h.setAttribute("aria-checked",c));a.F||(a.j.borderLeft="0");_.he(a.m)&&(a.j.paddingLeft=_.Nl(a.m));a.j.fontWeight=c?"500":"";a.j.backgroundColor=b?"#ebebeb":"#fff"};_.jF=function(a,b,c,d){return new iF(a,b,c,d,gF)};
kF=function(a,b,c,d,e){this.h=_.Lm("li",a);this.h.tabIndex=-1;this.h.setAttribute("role","menuitemcheckbox");this.h.setAttribute("aria-label",b);_.Hh(this.h);this.j=document.createElement("span");this.j.style["mask-image"]='url("'+_.Zq["checkbox_checked.svg"]+'")';this.j.style["-webkit-mask-image"]='url("'+_.Zq["checkbox_checked.svg"]+'")';this.m=document.createElement("span");this.m.style["mask-image"]='url("'+_.Zq["checkbox_empty.svg"]+'")';this.m.style["-webkit-mask-image"]='url("'+_.Zq["checkbox_empty.svg"]+
'")';a=_.Lm("span",this.h);a.appendChild(this.j);a.appendChild(this.m);this.C=_.Lm("label",this.h);this.C.textContent=b;BE(this.h,e);b=_.gt.Wb();_.$u(this.h);wE(this.h);this.m.style.height=this.j.style.height="1em";this.m.style.width=this.j.style.width="1em";this.m.style.transform=this.j.style.transform="translateY(0.15em)";this.C.style.cursor="inherit";this.h.style.backgroundColor="#fff";this.h.style.whiteSpace="nowrap";this.h.style[b?"paddingLeft":"paddingRight"]=_.Nl(8);dua(this,c,d);_.$m(eua,
this.h);_.Wl(this.h,"checkbox-menu-item")};dua=function(a,b,c){_.Rl(a,"active_changed",function(){var d=!!a.get("active");_.mw(a.j,d);_.mw(a.m,!d);a.h.setAttribute("aria-checked",d)});_.yf(a.h,"mouseover",function(){fua(a,!0)});_.yf(a.h,"mouseout",function(){fua(a,!1)});b=gF(a.h,"click",b,c);b.bindTo("value",a);b.bindTo("display",a);a.bindTo("active",b)};fua=function(a,b){a.h.style.backgroundColor=b?"#ebebeb":"#fff"};
lF=function(a,b,c,d){var e=this.h=_.Lm("li",a);BE(e,d);_.Hm(b,e);e.style.backgroundColor="#fff";e.tabIndex=-1;e.setAttribute("role","menuitemradio");e.setAttribute("aria-checked",!1);_.Hh(e);_.Af(this,"active_changed",this,function(){var f=this.get("active")||!1;e.style.fontWeight=f?"500":"";e.setAttribute("aria-checked",f)});_.Af(this,"enabled_changed",this,function(){var f=0!=this.get("enabled");e.style.color=f?"black":"gray";(f=f?d.title:d.Sv)&&e.setAttribute("title",f)});a=gF(e,"click",c);a.bindTo("value",
this);a.bindTo("display",this);a.bindTo("enabled",this);this.bindTo("active",a);_.Ql(e,"mouseover",this,function(){0!=this.get("enabled")&&(e.style.backgroundColor="#ebebeb",e.style.color="#000")});_.yf(e,"mouseout",function(){e.style.backgroundColor="#fff";e.style.color="#565656"})};
gua=function(a){var b=_.Lm("div",a);b.style.margin="1px 0";b.style.borderTop="1px solid #ebebeb";a=this.get("display");b&&(b.setAttribute("aria-hidden","true"),b.style.visibility=b.style.visibility||"inherit",b.style.display=a?"":"none");_.Af(this,"display_changed",this,function(){_.mw(b,0!=this.get("display"))})};
mF=function(a,b,c,d,e,f){f=f||{};this.G=a;this.D=b;a=this.h=_.Lm("ul",b);a.style.backgroundColor="white";a.style.listStyle="none";a.style.margin=a.style.padding=0;_.Mm(a,-1);a.style.padding=_.Nl(2);lta(a,_.Nl(_.Ez(d)));_.rw(a,"0 1px 4px -1px rgba(0,0,0,0.3)");f.position?_.Km(a,f.position,f.fz):(a.style.position="absolute",a.style.top="100%",a.style.left="0",a.style.right="0");wE(a);_.nw(a);this.m=[];this.j=null;this.C=e;e=this.C.id||(this.C.id=_.Ih());a.setAttribute("role","menu");for(a.setAttribute("aria-labelledby",
e);_.Yd(c);){e=c.shift();f=_.A(e);for(b=f.next();!b.done;b=f.next()){b=b.value;var g=void 0,h={title:b.alt,Sv:b.C||void 0,fontSize:EE(d),padding:[1+d>>3]};null!=b.m?g=new kF(a,b.label,b.h,b.m,h):g=new lF(a,b.label,b.h,h);g.bindTo("value",this.G,b.vf);g.bindTo("display",b);g.bindTo("enabled",b);this.m.push(g)}f=_.v(c,"flat").call(c);f.length&&(b=new gua(a),hua(b,e,f))}};
hua=function(a,b,c){function d(){function e(f){f=_.A(f);for(var g=f.next();!g.done;g=f.next())if(0!=g.value.get("display"))return!0;return!1}a.set("display",e(b)&&e(c))}_.ib(b.concat(c),function(e){_.L(e,"display_changed",d)})};
kua=function(a){var b=a.h;if(!b.listeners){var c=a.D;b.listeners=[_.yf(c,"mouseout",function(){b.timeout=window.setTimeout(function(){a.set("active",!1)},1E3)}),_.Ql(c,"mouseover",a,a.F),_.yf(document.body,"click",function(e){for(e=e.target;e;){if(e==c)return;e=e.parentNode}a.set("active",!1)}),_.yf(b,"keydown",function(e){return iua(a,e)}),_.yf(b,"blur",function(){setTimeout(function(){b.contains(document.activeElement)||a.set("active",!1)},0)},!0)]}_.ow(b);if(a.D.contains(document.activeElement)){var d=
_.v(a.m,"find").call(a.m,function(e){return!1!==e.get("display")});d&&jua(a,d)}};iua=function(a,b){if("Escape"===b.key||"Esc"===b.key)a.set("active",!1);else{var c=a.m.filter(function(e){return!1!==e.get("display")}),d=a.j?c.indexOf(a.j):0;if("ArrowUp"===b.key)d--;else if("ArrowDown"===b.key)d++;else if("Home"===b.key)d=0;else if("End"===b.key)d=c.length-1;else return;d=(d+c.length)%c.length;jua(a,c[d])}};jua=function(a,b){a.j=b;b.kb().focus()};
nua=function(a,b,c,d){var e=this;this.h=a;this.h.setAttribute("role","menubar");this.m=d;this.j=[];_.L(this,"fontloaded_changed",function(){if(e.get("fontLoaded")){for(var h=e.j.length,k=0,l=0;l<h;++l){var m=_.Fi(e.j[l].parentNode),p=l==h-1;e.j[l].hr&&_.Km(e.j[l].hr.h,new _.Q(p?0:k,m.height),p);k+=m.width}e.j.length=0}});_.L(this,"mapsize_changed",function(){return lua(e)});_.L(this,"display_changed",function(){return lua(e)});d=b.length;for(var f=0,g=0;g<d;++g)f=mua(this,c,b[g],f,0==g,g==d-1);_.Iw();
a.style.cursor="pointer"};
mua=function(a,b,c,d,e,f){var g=document.createElement("div");a.h.appendChild(g);_.jta(g);_.$m(oua,a.h);_.sm(g,"gm-style-mtc");var h=_.Hm(c.label,a.h,!0);b=b(g,h,c.h,{title:c.alt,padding:[0,17],height:a.m,fontSize:EE(a.m),km:e,Po:f,Rr:!0,Mw:!0});g.style.position="relative";e=b.kb();new _.Eh(e,"focusin",function(){g.style.zIndex=1});new _.Eh(e,"focusout",function(){g.style.zIndex=0});c.vf&&b.bindTo("value",a,c.vf);e=null;h=_.Fi(g);c.j&&(e=new mF(a,g,c.j,a.m,b.kb(),{position:new _.Q(f?0:d,h.height),
fz:f}),pua(g,b,e));a.j.push({parentNode:g,hr:e});return d+=h.width};lua=function(a){var b=a.get("mapSize");b=!!(a.get("display")||b&&200<=b.width&&200<=b.height);_.mw(a.h,b);_.M(a.h,"resize")};
pua=function(a,b,c){new _.Eh(a,"click",function(){return c.set("active",!0)});new _.Eh(a,"mouseover",function(){b.get("active")&&c.set("active",!0)});_.yf(b,"active_changed",function(){b.get("active")||c.set("active",!1)});_.L(b,"keydown",function(d){"ArrowDown"!==d.key&&"ArrowUp"!==d.key||c.set("active",!0)});_.L(b,"click",function(){})};
nF=function(a,b,c){var d=this;_.Iw();a.style.cursor="pointer";wE(a);a.style.width=_.Nl(120);_.$m(oua,document.head);_.sm(a,"gm-style-mtc");var e=_.Hm("",a,!0),f=_.jF(a,e,null,{title:"\u0417\u043c\u0456\u043d\u0438\u0442\u0438 \u0441\u0442\u0438\u043b\u044c \u043c\u0430\u043f\u0438",gx:!0,ko:!0,Yp:!0,padding:[8,17],fontSize:18,km:!0,Po:!0}),g={},h=[b];b=_.A(b);for(var k=b.next();!k.done;k=b.next())k=k.value,"mapTypeId"==k.vf&&(g[k.h]=k.label),k.j&&h.push.apply(h,_.ma(k.j));this.addListener("maptypeid_changed",
function(){var m=g[d.get("mapTypeId")]||"";e.textContent=m});var l=f.kb();this.h=new mF(this,a,h,c,l);f.addListener("click",function(){d.h.set("active",!d.h.get("active"))});f.addListener("keydown",function(m){"ArrowDown"!==m.key&&"ArrowUp"!==m.key||d.h.set("active",!0)});this.h.addListener("active_changed",function(){l.setAttribute("aria-expanded",!!d.h.get("active"))});this.j=a};qua=function(a){var b=a.get("mapSize");b=!!(a.get("display")||b&&200<=b.width&&200<=b.height);_.mw(a.j,b);_.M(a.j,"resize")};
oF=function(a){this.W=a;this.h=!1};pF=function(a,b,c){a.get(b)!==c&&(a.h=!0,a.set(b,c),a.h=!1)};rua=function(a){var b=a.get("internalMapTypeId");_.Zd(a.W,function(c,d){d.mapTypeId==b&&d.Ck&&a.get(d.Ck)==d.value&&(b=c)});pF(a,"mapTypeId",b)};qF=function(a,b,c){this.j=a;this.m=_.ZE(a,b.getDiv());this.F=sua();_.nw(a);this.h=tua(this.m);_.yf(this.h,"click",function(){_.Tl(b,"Rc");_.Sl(161529)});this.W=b;this.C="";this.D=c};
uua=function(a,b){b?(a.style.fontFamily="Arial,sans-serif",a.style.fontSize="85%",a.style.fontWeight="bold",a.style.bottom="1px",a.style.padding="1px 3px"):(a.style.fontFamily="Roboto,Arial,sans-serif",a.style.fontSize=_.Nl(10));a.style.color="#000000";a.style.textDecoration="none";a.style.position="relative"};
tua=function(a){var b=_.Lm("a");b.target="_blank";b.rel="noopener";b.title="\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 Google \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0438 \u0432 \u043a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0438\u0445 \u0434\u0430\u043d\u0438\u0445 \u0430\u0431\u043e \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u0456 \u0434\u043e\u0440\u0456\u0433";fta(b,"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 Google \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0438 \u0432 \u043a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0438\u0445 \u0434\u0430\u043d\u0438\u0445 \u0430\u0431\u043e \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u0456 \u0434\u043e\u0440\u0456\u0433");
b.textContent="\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0443 \u043d\u0430 \u043a\u0430\u0440\u0442\u0456";uua(b);a.appendChild(b);return b};sua=function(){var a=new Image;a.src=_.Zq["bug_report_icon.svg"];a.alt="";a.style.width="12px";return a};
rF=function(a){var b=a.get("available");_.M(a.j,"resize");a.set("rmiLinkData",b?{label:"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0443 \u043d\u0430 \u043a\u0430\u0440\u0442\u0456",tooltip:"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 Google \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0438 \u0432 \u043a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0438\u0445 \u0434\u0430\u043d\u0438\u0445 \u0430\u0431\u043e \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u0456 \u0434\u043e\u0440\u0456\u0433",
url:a.C}:void 0)};vua=function(a){var b=a.get("available"),c=!1!==a.get("enabled");if(void 0===b)return!1;a=a.get("mapTypeId");return b&&_.jna(a)&&c&&!_.Qm()};wua=function(a,b,c){a.innerText="";b=_.A(b?[_.Zq["tilt_45_normal.svg"],_.Zq["tilt_45_hover.svg"],_.Zq["tilt_45_active.svg"]]:[_.Zq["tilt_0_normal.svg"],_.Zq["tilt_0_hover.svg"],_.Zq["tilt_0_active.svg"]]);for(var d=b.next();!d.done;d=b.next()){d=d.value;var e=document.createElement("img");e.alt="";e.style.width=_.Nl(EE(c));e.src=d;a.appendChild(e)}};
xua=function(a,b,c){for(var d=_.A([_.Zq["rotate_right_normal.svg"],_.Zq["rotate_right_hover.svg"],_.Zq["rotate_right_active.svg"]]),e=d.next();!e.done;e=d.next()){e=e.value;var f=document.createElement("img"),g=_.Nl(EE(b)+2);f.alt="";f.style.width=g;f.style.height=g;f.src=e;a.style.transform=c?"scaleX(-1)":"";a.appendChild(f)}};
yua=function(a){var b=_.Lm("div");b.style.position="relative";b.style.overflow="hidden";b.style.width=_.Nl(3*a/4);b.style.height=_.Nl(1);b.style.margin="0 5px";b.style.backgroundColor="rgb(230, 230, 230)";return b};
sF=function(a,b,c){var d=this,e=_.Bi[43]?"rgb(34, 34, 34)":"rgb(255, 255, 255)";_.$m(VE,c);this.F=b;this.J=a;this.h=_.Lm("div",a);this.h.style.backgroundColor=e;_.rw(this.h,"0 1px 4px -1px rgba(0,0,0,0.3)");AE(this.h,_.Nl(_.Ez(b)));this.m=_.Yq("\u041e\u0431\u0435\u0440\u043d\u0443\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u0437\u0430 \u0433\u043e\u0434\u0438\u043d\u043d\u0438\u043a\u043e\u0432\u043e\u044e \u0441\u0442\u0440\u0456\u043b\u043a\u043e\u044e");this.m.style.left="0";this.m.style.top=
"0";this.m.style.overflow="hidden";this.m.setAttribute("class","gm-control-active");_.Ei(this.m,new _.Eg(b,b));_.Om(this.m);xua(this.m,b,!1);this.h.appendChild(this.m);this.G=yua(b);this.h.appendChild(this.G);this.C=_.Yq("\u041e\u0431\u0435\u0440\u043d\u0443\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u043f\u0440\u043e\u0442\u0438 \u0433\u043e\u0434\u0438\u043d\u043d\u0438\u043a\u043e\u0432\u043e\u0457 \u0441\u0442\u0440\u0456\u043b\u043a\u0438");this.C.style.left="0";this.C.style.top="0";this.C.style.overflow=
"hidden";this.C.setAttribute("class","gm-control-active");_.Ei(this.C,new _.Eg(b,b));_.Om(this.C);xua(this.C,b,!0);this.h.appendChild(this.C);this.H=yua(b);this.h.appendChild(this.H);this.D=_.Yq("\u041d\u0430\u0445\u0438\u043b\u0438\u0442\u0438 \u043a\u0430\u0440\u0442\u0443");this.D.style.left=this.D.style.top="0";this.D.style.overflow="hidden";this.D.setAttribute("class","gm-tilt gm-control-active");wua(this.D,!1,b);_.Ei(this.D,new _.Eg(b,b));_.Om(this.D);this.h.appendChild(this.D);this.j=!0;this.m.addEventListener("click",
function(){var f=+d.get("heading")||0;d.set("heading",(f+270)%360)});this.C.addEventListener("click",function(){var f=+d.get("heading")||0;d.set("heading",(f+90)%360)});this.D.addEventListener("click",function(){d.j=!d.j;d.set("tilt",d.j?45:0)});_.L(this,"aerialavailableatzoom_changed",function(){return d.refresh()});_.L(this,"tilt_changed",function(){d.j=0!=d.get("tilt");d.refresh()});_.L(this,"mapsize_changed",function(){d.refresh()});_.L(this,"rotatecontrol_changed",function(){d.refresh()})};
zua=function(a,b,c){a=new sF(a,b,c);a.bindTo("mapSize",this);a.bindTo("rotateControl",this);a.bindTo("aerialAvailableAtZoom",this);a.bindTo("heading",this);a.bindTo("tilt",this)};
Bua=function(a,b,c){var d=this;this.Ta=a;this.j=!1;this.C=c;c=new _.bf(9==b.nodeType?b:b.ownerDocument||b.document);this.D=_.cf(c,"span");c.appendChild(b,this.D);this.h=_.cf(c,"div");c.appendChild(b,this.h);Aua(this,c);this.m=!0;b=_.Ih();c=document.createElement("span");c.id=b;c.textContent="Click to toggle between metric and imperial units";c.style.display="none";a.appendChild(c);a.setAttribute("aria-describedby",b);_.$h(a,"click",function(){d.m=!d.m;tF(d)});_.fl(this.C,function(){return tF(d)})};
Aua=function(a,b){CE(a.h,"position","relative");CE(a.h,"display","inline-block");a.h.style.height=_.Mw(8,!0);CE(a.h,"bottom","-1px");var c=_.cf(b,"div");b.appendChild(a.h,c);_.Nw(c,"100%",4);CE(c,"position","absolute");DE(c,0,0);c=_.cf(b,"div");b.appendChild(a.h,c);_.Nw(c,4,8);DE(c,0,0);CE(c,"backgroundColor","#fff");c=_.cf(b,"div");b.appendChild(a.h,c);_.Nw(c,4,8);CE(c,"position","absolute");CE(c,"backgroundColor","#fff");CE(c,"right","0px");CE(c,"bottom","0px");c=_.cf(b,"div");b.appendChild(a.h,
c);CE(c,"position","absolute");CE(c,"backgroundColor","#666");c.style.height=_.Mw(2,!0);CE(c,"left","1px");CE(c,"bottom","1px");CE(c,"right","1px");c=_.cf(b,"div");b.appendChild(a.h,c);CE(c,"position","absolute");_.Nw(c,2,6);DE(c,1,1);CE(c,"backgroundColor","#666");c=_.cf(b,"div");b.appendChild(a.h,c);_.Nw(c,2,6);CE(c,"position","absolute");CE(c,"backgroundColor","#666");CE(c,"bottom","1px");CE(c,"right","1px")};
tF=function(a){var b=a.C.get();b&&(b*=80,b=a.m?Cua(b/1E3,b,!0):Cua(b/1609.344,3.28084*b,!1),a.D.textContent=b.Tv+"\u00a0",a.Ta.setAttribute("aria-label",b.Vr),a.Ta.title=b.Vr,a.h.style.width=_.Mw(b.Ey+4,!0),_.M(a.Ta,"resize"))};
Cua=function(a,b,c){var d=a,e=c?"\u043a\u043c":"\u043c\u0438\u043b.";1>a&&(d=b,e=c?"\u043c":"\u0444\u0442");for(b=1;d>=10*b;)b*=10;d>=5*b&&(b*=5);d>=2*b&&(b*=2);d=Math.round(80*b/d);var f=c?"Map Scale: "+b+" km per "+d+" pixels":"Map Scale: "+b+" mi per "+d+" pixels";1>a&&(f=c?"Map Scale: "+b+" m per "+d+" pixels":"Map Scale: "+b+" ft per "+d+" pixels");return{Ey:d,Tv:b+" "+e,Vr:f}};
Eua=function(a){var b=this;this.Ta=document.createElement("div");this.Ta.style.display="inline-flex";this.m=0;this.C=new _.ni(function(){return b.update(b.m)},0);this.h=a.yv;this.j=Dua(this,a.RA);a=_.A(this.h);for(var c=a.next();!c.done;c=a.next())c=c.value,c.bc(),c=c.Td(),this.Ta.appendChild(c),_.L(c,"resize",function(){_.oi(b.C)})};Dua=function(a,b){return b?(b.every(function(c){return _.v(a.h,"includes").call(a.h,c)}),b):a.h};
uF=function(a,b,c,d){a.innerText="";b=_.A(0===b?2===c?[_.Zq["zoom_in_normal_dark.svg"],_.Zq["zoom_in_hover_dark.svg"],_.Zq["zoom_in_active_dark.svg"],_.Zq["zoom_in_disable_dark.svg"]]:[_.Zq["zoom_in_normal.svg"],_.Zq["zoom_in_hover.svg"],_.Zq["zoom_in_active.svg"],_.Zq["zoom_in_disable.svg"]]:2===c?[_.Zq["zoom_out_normal_dark.svg"],_.Zq["zoom_out_hover_dark.svg"],_.Zq["zoom_out_active_dark.svg"],_.Zq["zoom_out_disable_dark.svg"]]:[_.Zq["zoom_out_normal.svg"],_.Zq["zoom_out_hover.svg"],_.Zq["zoom_out_active.svg"],
_.Zq["zoom_out_disable.svg"]]);for(c=b.next();!c.done;c=b.next()){c=c.value;var e=document.createElement("img");e.style.width=e.style.height=_.Nl(EE(d));e.src=c;e.alt="";a.appendChild(e)}};
wF=function(a,b,c,d){var e=this;this.C=a;this.j=b;this.h=_.Lm("div",a);_.Om(this.h);_.Nm(this.h);_.rw(this.h,"0 1px 4px -1px rgba(0,0,0,0.3)");AE(this.h,_.Nl(_.Ez(b)));this.h.style.cursor="pointer";_.$m(VE,d);_.yf(this.h,"mouseover",function(){e.set("mouseover",!0)});_.yf(this.h,"mouseout",function(){e.set("mouseover",!1)});this.D=Fua(this,this.h,0);this.m=_.Lm("div",this.h);this.m.style.position="relative";this.m.style.overflow="hidden";this.m.style.width=_.Nl(3*b/4);this.m.style.height=_.Nl(1);
this.m.style.margin="0 5px";this.F=Fua(this,this.h,1);_.L(this,"display_changed",function(){return Gua(e)});_.L(this,"mapsize_changed",function(){return Gua(e)});_.L(this,"maptypeid_changed",function(){var f=e.get("mapTypeId");e.set("controlStyle",("satellite"===f||"hybrid"===f)&&_.Bi[43]||"streetview"==f?2:1)});_.L(this,"controlstyle_changed",function(){var f=e.get("controlStyle");if(null!=f){var g=vF[f];uF(e.D,0,f,e.j);uF(e.F,1,f,e.j);e.h.style.backgroundColor=g.backgroundColor;e.m.style.backgroundColor=
g.Zq}})};Fua=function(a,b,c){var d=_.Yq(0===c?"\u0417\u0431\u0456\u043b\u044c\u0448\u0438\u0442\u0438":"\u0417\u043c\u0435\u043d\u0448\u0438\u0442\u0438");b.appendChild(d);_.yf(d,"click",function(){var e=0===c?1:-1;a.set("zoom",a.get("zoom")+e)});d.setAttribute("class","gm-control-active");d.style.overflow="hidden";b=a.get("controlStyle");uF(d,c,b,a.j);return d};
Gua=function(a){var b=a.get("mapSize");if(b&&200<=b.width&&200<=b.height||a.get("display")){_.ow(a.C);b=a.j;var c=2*a.j+1;a.h.style.width=_.Nl(b);a.h.style.height=_.Nl(c);a.C.dataset.controlWidth=String(b);a.C.dataset.controlHeight=String(c);_.M(a.C,"resize");b=a.D.style;b.width=_.Nl(a.j);b.height=_.Nl(a.j);b.left=b.top="0";a.m.style.top="0";b=a.F.style;b.width=_.Nl(a.j);b.height=_.Nl(a.j);b.left=b.top="0"}else _.nw(a.C)};
xF=function(a,b,c,d){a=this.h=_.Lm("div");_.zE(a);b=new wF(a,b,c,d);b.bindTo("mapSize",this);b.bindTo("display",this,"display");b.bindTo("mapTypeId",this);b.bindTo("zoom",this);b.bindTo("zoomRange",this);this.Yk=b};Hua=function(a){a.Yk&&(a.Yk.unbindAll(),a.Yk=null)};
zF=function(a,b,c){_.zE(a);_.Mm(a,1000001);this.h=a;a=_.Lm("div",a);b=_.ZE(a,b);this.D=a;a=_.Yq("\u041a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0456 \u0434\u0430\u043d\u0456");b.appendChild(a);a.textContent="\u041a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0456 \u0434\u0430\u043d\u0456";a.style.color="#000000";a.style.display="inline-block";a.style.fontFamily="inherit";a.style.lineHeight="inherit";_.kw(a,"click",this);this.m=a;b=_.Lm("span",b);b.style.display=
"none";this.j=b;this.C=c;yF(this)};yF=function(a){var b=a.get("attributionText")||"\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f \u043c\u043e\u0436\u0435 \u0431\u0443\u0442\u0438 \u0437\u0430\u0445\u0438\u0449\u0435\u043d\u0435 \u0430\u0432\u0442\u043e\u0440\u0441\u044c\u043a\u0438\u043c \u043f\u0440\u0430\u0432\u043e\u043c";a.C&&(b=b.replace("Map data","Map Data"));_.sw(a.j,b);_.M(a.h,"resize")};
AF=function(a){this.m=a.ownerElement;this.j=document.createElement("div");this.j.style.color="#222";this.j.style.maxWidth="280px";this.h=new _.fr({content:this.j,se:a.se,kd:a.kd,ownerElement:this.m,title:"\u041a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0456 \u0434\u0430\u043d\u0456"});_.Wl(this.h.element,"copyright-dialog-view")};
BF=function(a){_.yE(a,"gmnoprint");_.sm(a,"gmnoscreen");this.h=a;a=this.j=_.Lm("div",a);a.style.fontFamily="Roboto,Arial,sans-serif";a.style.fontSize=_.Nl(11);a.style.color="#000000";a.style.direction="ltr";a.style.textAlign="right";a.style.backgroundColor="#f5f5f5"};
CF=function(a,b){_.zE(a);_.Mm(a,1000001);this.h=a;this.j=_.ZE(a,b);this.m=a=_.Lm("a",this.j);a.style.textDecoration="none";a.style.cursor="pointer";a.textContent="\u0423\u043c\u043e\u0432\u0438 \u0432\u0438\u043a\u043e\u0440\u0438\u0441\u0442\u0430\u043d\u043d\u044f";eta(a,_.Ria);a.target="_blank";a.setAttribute("rel","noopener");a.style.color="#000000";a.addEventListener("click",function(){})};
Iua=function(a,b,c,d){var e=c instanceof _.Yg;e=new bF(_.Lm("div"),a,e?2:1);e.bindTo("keyboardShortcutsShown",this);e.bindTo("fontLoaded",this);d=new zF(document.createElement("div"),a,d);d.bindTo("attributionText",this);d.bindTo("fontLoaded",this);d.bindTo("isCustomPanorama",this);var f=c.__gm.get("innerContainer"),g=new AF({kd:a,se:function(){_.Rm(f).catch(function(){})},ownerElement:b});g.bindTo("attributionText",this);_.L(d,"click",function(){g.set("visible",!0)});b=new BF(document.createElement("div"));
b.bindTo("attributionText",this);a=new CF(document.createElement("div"),a);a.bindTo("fontLoaded",this);a.bindTo("mapTypeId",this);d.bindTo("mapTypeId",this);c&&_.Bi[28]?(d.bindTo("hidden",c,"hideLegalNotices"),b.bindTo("hidden",c,"hideLegalNotices"),a.bindTo("hidden",c,"hideLegalNotices")):(d.bindTo("isCustomPanorama",this),b.bindTo("hidden",this,"isCustomPanorama"));this.j=d;this.m=b;this.C=a;this.h=e};DF=function(a){this.h=a};
EF=function(a,b){_.Om(a);_.Nm(a);a.style.fontFamily="Roboto,Arial,sans-serif";a.style.fontSize=_.Nl(Math.round(11*b/40));a.style.textAlign="center";_.rw(a,"rgba(0, 0, 0, 0.3) 0px 1px 4px -1px");a.dataset.controlWidth=String(b);a.style.cursor="pointer";this.j=[];this.h=b;this.m=a};Jua=function(a,b,c){_.yf(b,"mouseover",function(){b.style.color="#bbb";b.style.fontWeight="bold"});_.yf(b,"mouseout",function(){b.style.color="#999";b.style.fontWeight="400"});_.Ql(b,"click",a,function(){a.set("pano",c)})};
FF=function(a,b){var c=this;this.D=a;_.sm(a,"gm-svpc");a.setAttribute("dir","ltr");a.setAttribute("title","\u041f\u0435\u0440\u0435\u0442\u044f\u0433\u043d\u0456\u0442\u044c \u0447\u043e\u043b\u043e\u0432\u0456\u0447\u043a\u0430 \u043d\u0430 \u043a\u0430\u0440\u0442\u0443, \u0449\u043e\u0431 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0438 \u041f\u0435\u0440\u0435\u0433\u043b\u044f\u0434 \u0432\u0443\u043b\u0438\u0446\u044c");a.style.backgroundColor="#fff";this.j={ao:null,active:null,Zn:null};this.h=
b;this.m=!0;Kua(this);this.set("position",_.tE.ss.offset);_.Ql(a,"mouseover",this,this.F);_.Ql(a,"mouseout",this,this.G);a=this.C=new _.qD(a);a.bindTo("position",this);_.Cf(a,"dragstart",this);_.Cf(a,"drag",this);_.Cf(a,"dragend",this);_.L(a,"dragend",function(){c.set("position",_.tE.ss.offset)});_.L(this,"mode_changed",function(){var d=c.get("mode");c.C.get("enabled")||c.C.set("enabled",!0);Lua(c,d)});_.L(this,"display_changed",function(){return Mua(c)});_.L(this,"mapsize_changed",function(){return Mua(c)});
this.set("mode",1)};
Kua=function(a){for(var b in a.j){var c=a.j[b];c&&c.parentNode&&_.Xe(c);a.j[b]=null}b=a.D;if(a.m){_.ow(b);c=new _.Eg(a.h,a.h);_.rw(b,"0 1px 4px -1px rgba(0,0,0,0.3)");AE(b,_.Nl(40<a.h?Math.round(a.h/20):2));b.style.width=_.Nl(c.width);b.style.height=_.Nl(c.height);var d=32>a.h?a.h-2:40>a.h?30:10+a.h/2,e=_.Lm("div",b);e.style.position="absolute";e.style.left="50%";e.style.top="50%";var f=_.Ve("IMG");a.j.ao=f;f.src=_.Zq["pegman_dock_normal.svg"];f.style.width=f.style.height=_.Nl(d);f.style.position=
"absolute";f.style.transform="translate(-50%, -50%)";f.alt="\u0427\u043e\u043b\u043e\u0432\u0456\u0447\u043e\u043a \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443 \u0432\u0443\u043b\u0438\u0446\u044c";f.style.pointerEvents="none";e.appendChild(f);f=_.Ve("IMG");a.j.active=f;f.src=_.Zq["pegman_dock_active.svg"];f.style.display="none";f.style.width=f.style.height=_.Nl(d);f.style.position="absolute";f.style.transform="translate(-50%, -50%)";f.alt="\u0427\u043e\u043b\u043e\u0432\u0456\u0447\u043e\u043a \u0443\u0433\u043e\u0440\u0456 \u043a\u0430\u0440\u0442\u0438";
f.style.pointerEvents="none";e.appendChild(f);f=_.Ve("IMG");a.j.Zn=f;f.style.display="none";f.style.width=f.style.height=_.Nl(4*d/3);f.style.position="absolute";f.style.transform="translate(-60%, -45%)";f.style.pointerEvents="none";f.alt="\u0427\u043e\u043b\u043e\u0432\u0456\u0447\u043e\u043a \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443 \u0432\u0443\u043b\u0438\u0446\u044c";e.appendChild(f);f.src=_.Zq["pegman_dock_hover.svg"];b.dataset.controlWidth=String(c.width);b.dataset.controlHeight=
String(c.height);_.M(b,"resize");Lua(a,a.get("mode"))}else _.nw(b),_.M(b,"resize")};Lua=function(a,b){a.m&&(a=a.j,a.ao.style.display=a.Zn.style.display=a.active.style.display="none",1==b?a.ao.style.display="":2==b?a.Zn.style.display="":a.active.style.display="")};Mua=function(a){var b=a.get("mapSize");b=!!a.get("display")||!!(b&&200<=b.width&&b&&200<=b.height);a.m!=b&&(a.m=b,Kua(a))};
GF=function(a){var b=this;a={clickable:!1,crossOnDrag:!1,draggable:!0,map:a,mapOnly:!0,pegmanMarker:!0,zIndex:1E6};this.N=_.tE.dh;this.X=_.tE.gz;this.C=0;this.H=this.F=-1;this.m=0;this.D=this.G=null;this.j=_.cg("mode");this.h=_.dg("mode");var c=new _.Zg(a);this.T=c;c.setDraggable(!0);var d=new _.Zg(a);this.J=d;var e=new _.Zg(a);this.K=e;this.h(1);this.set("heading",0);c.bindTo("icon",this,"pegmanIcon");c.bindTo("position",this,"dragPosition");c.bindTo("dragging",this);d.bindTo("icon",this,"lilypadIcon");
_.L(this,"position_changed",function(){d.set("position",b.get("position"))});d.bindTo("dragging",this);e.set("cursor",_.qia);e.set("icon",rta(this.X,0));_.L(this,"dragposition_changed",function(){e.set("position",b.get("dragPosition"))});e.bindTo("dragging",this);_.L(this,"dragstart",this.Zt);_.L(this,"drag",this.au);_.L(this,"dragend",this.Yt);_.Cf(c,"dragstart",this);_.Cf(c,"drag",this);_.Cf(c,"dragend",this)};
Pua=function(a){var b=a.j(),c=_.iD(b);a.T.setVisible(c||7==b);var d=a.set;c?(b=a.j()-3,b=rta(a.N,b)):7==b?(b=Nua(a),a.H!=b&&(a.H=b,a.G={url:Oua[b],scaledSize:new _.Eg(49,52),anchor:new _.Q(25,35)}),b=a.G):b=void 0;d.call(a,"pegmanIcon",b)};Qua=function(a){a.J.setVisible(!1);a.K.setVisible(_.iD(a.j()))};Nua=function(a){(a=_.Uu(a.get("heading"))%360)||(a=0);0>a&&(a+=360);return Math.round(a/360*16)%16};
HF=function(a,b,c,d,e,f,g,h,k,l){this.W=a;this.ib=f;this.Ej=e;this.Ca=g;this.F=h;this.G=l||null;this.zx=d;this.C=this.m=!1;this.D=null;this.jn(1);Rua(this,c,b);this.h=new _.sD(k);k||(this.h.bindTo("mapHeading",this),this.h.bindTo("tilt",this));this.h.bindTo("client",this);this.h.bindTo("client",a,"svClient");this.j=this.Bs=null;this.Fd=_.uD(c,d)};Sua=function(a,b){return _.ee(b-(a||0),0,360)};
Rua=function(a,b,c){var d=a.W.__gm,e=new FF(b,a.F);e.bindTo("mode",a);e.bindTo("mapSize",a);e.bindTo("display",a);var f=new GF(a.W);f.bindTo("mode",a);f.bindTo("dragPosition",a);f.bindTo("position",a);var g=new _.hD(["mapHeading","streetviewHeading"],"heading",Sua);g.bindTo("streetviewHeading",a,"heading");g.bindTo("mapHeading",a.W,"heading");f.bindTo("heading",g);a.bindTo("pegmanDragging",f,"dragging");d.bindTo("pegmanDragging",a);_.Af(e,"dragstart",a,function(){var h=this;this.Fd=_.uD(b,this.zx);
_.gf("streetview").then(function(k){if(!h.Bs){var l=(0,_.La)(h.Ej.getUrl,h.Ej),m=d.get("panes");k=h.Bs=new k.uu(m.floatPane,l,h.ib);k.bindTo("description",h);k.bindTo("mode",h);k.bindTo("thumbnailPanoId",h,"panoId");k.bindTo("pixelBounds",d);l=new _.gD(function(p){p=new _.uq(h.W,h.Ca,p);h.Ca.Wa(p);return p});l.bindTo("latLngPosition",f,"dragPosition");k.bindTo("pixelPosition",l)}})});_.ib(["dragstart","drag","dragend"],function(h){_.L(e,h,function(){_.M(f,h,{latLng:f.get("position"),pixel:e.get("position")})})});
_.L(e,"position_changed",function(){var h=e.get("position");(h=c({clientX:h.x+a.Fd.x,clientY:h.y+a.Fd.y}))&&f.set("dragPosition",h)});_.L(f,"dragend",(0,_.La)(a.ns,a,!1));_.L(f,"hover",(0,_.La)(a.ns,a,!0))};Tua=function(a){var b=a.W.overlayMapTypes,c=a.h;b.forEach(function(d,e){d==c&&b.removeAt(e)});a.m=!1};Uua=function(a){var b=a.get("projection");b&&b.j&&(a.W.overlayMapTypes.push(a.h),a.m=!0)};
JF=function(a,b){this.Ta=a;this.Ej=b;IF()?(b=a,_.zE(b),b.style.fontSize="10px",b.style.height="17px",b.style.backgroundColor="#f5f5f5",b.style.border="1px solid #dcdcdc",b.style.lineHeight="19px"):(b=a,a=_.ZE(a),$E(b));this.h=_.Lm("a",a);IF()?uua(this.h,!0):(this.h.style.textDecoration="none",this.h.style.color="#fff");this.h.setAttribute("target","_new");a=(IF(),"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0443");_.Hm(a,
this.h);this.h.setAttribute("title","\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0442\u0435 Google \u043f\u0440\u043e \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0443 \u0456\u0437 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f\u043c \u0443 \u0440\u0435\u0436\u0438\u043c\u0456 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443 \u0432\u0443\u043b\u0438\u0446\u044c");fta(this.h,"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0442\u0435 Google \u043f\u0440\u043e \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0443 \u0456\u0437 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f\u043c \u0443 \u0440\u0435\u0436\u0438\u043c\u0456 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443 \u0432\u0443\u043b\u0438\u0446\u044c")};
IF=function(){return"CH"===_.Md(_.Pd(_.hg))};Vua=function(a){a={content:(new _.xD({pg:a.pg,qg:a.qg,ownerElement:a.ownerElement,Tk:!0,Fi:a.Fi})).element,se:a.se,kd:a.kd,ownerElement:a.ownerElement,title:"\u041a\u043e\u043c\u0431\u0456\u043d\u0430\u0446\u0456\u0457 \u043a\u043b\u0430\u0432\u0456\u0448"};a=new _.fr(a);_.Wl(a.element,"keyboard-shortcuts-dialog-view");return a};Wua=function(){return"@media print {  .gm-style .gmnoprint, .gmnoprint {    display:none  }}@media screen {  .gm-style .gmnoscreen, .gmnoscreen {    display:none  }}"};
KF=function(a){var b=this;this.Fa=new _.ni(function(){b.F[1]&&Xua(b);b.F[0]&&Yua(b);b.F[3]&&Zua(b);b.F={};b.get("disableDefaultUI")&&!b.h&&(_.P(b.W,"Cdn"),_.rg(b.W,148245))},0);this.G=a.Xr||null;this.Z=a.Gg;this.Ga=a.Ax||null;this.m=a.controlSize;this.wb=a.vv||null;this.W=a.map||null;this.h=a.Dz||null;this.Ka=this.W||this.h;this.Nb=a.ct;this.Ec=a.Cz||null;this.Ca=a.Ha||null;this.Eb=!!a.kx;this.je=!!a.qg;this.dd=!!a.pg;this.Mb=this.Ab=this.Fb=!1;this.D=this.kc=this.da=this.ea=null;this.J=a.ur;this.xb=
_.Yq("\u041f\u0435\u0440\u0435\u043c\u043a\u043d\u0443\u0442\u0438 \u043f\u043e\u0432\u043d\u043e\u0435\u043a\u0440\u0430\u043d\u043d\u0438\u0439 \u0440\u0435\u0436\u0438\u043c");this.T=null;this.Ie=a.Ol;this.K=null;this.Ya=!1;this.na=[];this.Y=null;this.Nd={};this.F={};this.X=this.ca=this.ba=this.ja=null;this.Ra=_.Lm("div");this.H=null;this.ya=!1;_.Om(this.Ra);_.an(Wua,this.J);var c=this.pb=new eF(_.K(_.Pd(_.hg).o,15));c.bindTo("center",this);c.bindTo("zoom",this);c.bindTo("mapTypeId",this);c.bindTo("pano",
this);c.bindTo("position",this);c.bindTo("pov",this);c.bindTo("heading",this);c.bindTo("tilt",this);a.map&&_.L(c,"url_changed",function(){a.map.set("mapUrl",c.get("url"))});var d=new DF(_.Pd(_.hg));d.bindTo("center",this);d.bindTo("zoom",this);d.bindTo("mapTypeId",this);d.bindTo("pano",this);d.bindTo("heading",this);this.me=d;$ua(this);this.C=ava(this);this.N=null;bva(this);this.aa=null;cva(this);this.j=null;a.Ss&&dva(this);Zua(this);eva(this,a.Rq);this.ea=new Xta(this.C.h,this.Z);this.Z.insertBefore(this.ea.Ta,
this.Z.children[0]);this.ne=fva(this);this.keyboardShortcuts_changed();_.Bi[35]&&gva(this);hva(this)};fva=function(a){if(a.W){var b=[a.C.h,a.C.j,a.C.m,a.aa,a.C.C];a.j&&b.push(a.j)}else b=[a.C.h,a.C.j,a.C.m,a.C.C,a.N];b=new Eua({yv:b});a.G.addElement(b.Ta,12,!0);return b};
bva=function(a){if(a.h){var b=document.createElement("div");a.N=new JF(b,a.Nb);a.N.bindTo("pov",a.h);a.N.bindTo("pano",a.h);a.N.bindTo("takeDownUrl",a.h);a.h.set("rmiWidth",b.offsetWidth);_.Bi[17]&&(a.N.bindTo("visible",a.h,"reportErrorControl"),a.h.bindTo("rmiLinkData",a.N))}};hva=function(a){_.gf("util").then(function(b){b.Df.h(function(){a.ya=!0;iva(a);a.H&&(a.H.set("display",!1),a.H.unbindAll(),a.H=null)})})};
nva=function(a){if(jva(a)!=a.kc||kva(a)!=a.Fb||lva(a)!=a.Mb||LF(a)!=a.Ya||mva(a)!=a.Ab)a.F[1]=!0;a.F[0]=!0;_.oi(a.Fa)};MF=function(a){return a.get("disableDefaultUI")};LF=function(a){var b=a.get("streetViewControl"),c=a.get("disableDefaultUI"),d=!!a.get("size");if(void 0!==b||c)_.P(a.W,b?"Cvy":"Cvn"),_.rg(a.W,b?148260:148261);null==b&&(b=!c);a=d&&!a.h;return b&&a};ova=function(a){return!a.get("disableDefaultUI")&&!!a.h};
eva=function(a,b){var c=a.G;_.ib(b,function(d,e){if(d){var f=function(g){if(g){var h=g.index;_.he(h)||(h=1E3);h=Math.max(h,-999);_.Mm(g,Math.min(999999,_.Uu(g.style.zIndex||0)));c.addElement(g,e,!1,h)}};d.forEach(f);_.L(d,"insert_at",function(g){f(d.getAt(g))});_.L(d,"remove_at",function(g,h){c.xf(h)})}})};gva=function(a){if(a.W){var b=new ME(document.createElement("div"));b.bindTo("card",a.W.__gm);b=b.getDiv();a.G.addElement(b,1,!0,.1)}};
Zua=function(a){a.T&&(a.T.unbindAll(),Rta(a.T),a.T=null,a.G.xf(a.xb));var b=_.Yq("\u041f\u0435\u0440\u0435\u043c\u043a\u043d\u0443\u0442\u0438 \u043f\u043e\u0432\u043d\u043e\u0435\u043a\u0440\u0430\u043d\u043d\u0438\u0439 \u0440\u0435\u0436\u0438\u043c"),c=new Sta(a.J,b,a.Ie,a.m);c.bindTo("display",a,"fullscreenControl");c.bindTo("disableDefaultUI",a);c.bindTo("mapTypeId",a);var d=a.get("fullscreenControlOptions")||{};a.G.addElement(b,d&&d.position||7,!0,-1007);a.T=c;a.xb=b};
ava=function(a){var b=new Iua(a.Z,a.J,a.Ka,a.Eb);b.bindTo("size",a);b.bindTo("rmiWidth",a);b.bindTo("attributionText",a);b.bindTo("fontLoaded",a);b.bindTo("mapTypeId",a);b.bindTo("isCustomPanorama",a);b.bindTo("logoWidth",a);b.h.addListener("click",function(){a.da||(a.da=pva(a));a.Ka.__gm.get("developerProvidedDiv").appendChild(a.da.element);a.da.show()});return b};
pva=function(a){var b=a.Ka.__gm,c=b.get("innerContainer"),d=b.get("developerProvidedDiv"),e=Vua({pg:a.dd,qg:a.je,se:function(){_.Rm(c).catch(function(){})},kd:a.Z,ownerElement:d,Fi:a.W?"map":"street_view"});e.addListener("hide",function(){d.removeChild(e.element)});return e};$ua=function(a){if(!_.Bi[2]){var b=!!_.Bi[21];a.W?b=bua(a.W,a.pb,b):(b=new fF(a.h,a.pb,b),aua(b,!0));b=b.getDiv();a.G.addElement(b,10,!0,-1E3);a.set("logoWidth",b.offsetWidth)}};
dva=function(a){if(a.W){var b=_.Pd(_.hg);a.j=new qF(document.createElement("div"),a.W,_.K(b.o,15));a.j.bindTo("available",a,"rmiAvailable");a.j.bindTo("bounds",a);_.Bi[17]?(a.j.bindTo("enabled",a,"reportErrorControl"),a.W.bindTo("rmiLinkData",a.j)):a.j.set("enabled",!0);a.j.bindTo("mapTypeId",a);a.j.bindTo("sessionState",a.me);a.bindTo("rmiWidth",a.j,"width");_.L(a.j,"rmilinkdata_changed",function(){var c=a.j.get("rmiLinkData");a.W.set("rmiUrl",c&&c.url)})}};
iva=function(a){a.fa&&(a.fa.unbindAll&&a.fa.unbindAll(),a.fa=null);a.ja&&(a.ja.unbindAll(),a.ja=null);a.ba&&(a.ba.unbindAll(),a.ba=null);a.Y&&(qva(a,a.Y),_.cj(a.Y.Aa),a.Y=null)};
Yua=function(a){iva(a);if(a.Ga&&!a.ya){var b=rva(a);if(b){var c=_.Lm("div");_.zE(c);c.style.margin=_.Nl(a.m>>2);_.yf(c,"mouseover",function(){_.Mm(c,1E6)});_.yf(c,"mouseout",function(){_.Mm(c,0)});_.Mm(c,0);var d=a.get("mapTypeControlOptions")||{},e=a.ba=new yta(a.Ga,d.mapTypeIds);e.bindTo("aerialAvailableAtZoom",a);e.bindTo("zoom",a);var f=e.C;a.G.addElement(c,d.position||1,!1,.2);d=null;2==b?(d=new nF(c,f,a.m),e.bindTo("mapTypeId",d)):d=new nua(c,f,_.jF,a.m);b=a.ja=new oF(e.m);b.set("labels",!0);
d.bindTo("mapTypeId",b,"internalMapTypeId");d.bindTo("labels",b);d.bindTo("terrain",b);d.bindTo("tilt",a,"desiredTilt");d.bindTo("fontLoaded",a);d.bindTo("mapSize",a,"size");d.bindTo("display",a,"mapTypeControl");b.bindTo("mapTypeId",a);_.M(c,"resize");a.Y={Aa:c,Sl:null};a.fa=d}}};
rva=function(a){if(!a.Ga)return null;var b=(a.get("mapTypeControlOptions")||{}).style||0,c=a.get("mapTypeControl"),d=MF(a);if(void 0===c&&d||void 0!==c&&!c)return _.P(a.W,"Cmn"),_.rg(a.W,148251),null;1==b?(_.P(a.W,"Cmh"),_.rg(a.W,148253)):2==b&&(_.P(a.W,"Cmd"),_.rg(a.W,148252));return 2==b||1==b?b:1};
sva=function(a,b){b=a.K=new xF(b,a.m,_.gt.Wb(),a.J);b.bindTo("zoomRange",a);b.bindTo("display",a,"zoomControl");b.bindTo("disableDefaultUI",a);b.bindTo("mapSize",a,"size");b.bindTo("mapTypeId",a);b.bindTo("zoom",a);return b.getDiv()};tva=function(a){var b=new _.Dz(OE,{ui:_.gt.Wb()}),c=new WE(b,a.m,a.J);c.bindTo("pov",a);c.bindTo("disableDefaultUI",a);c.bindTo("panControl",a);c.bindTo("mapSize",a,"size");return b.Aa};
uva=function(a){var b=_.Lm("div");_.zE(b);a.D=new zua(b,a.m,a.J);a.D.bindTo("mapSize",a,"size");a.D.bindTo("rotateControl",a);a.D.bindTo("heading",a);a.D.bindTo("tilt",a);a.D.bindTo("aerialAvailableAtZoom",a);return b};vva=function(a){var b=_.Lm("div"),c=a.ca=new EF(b,a.m);c.bindTo("pano",a);c.bindTo("floors",a);c.bindTo("floorId",a);return b};NF=function(a){a.F[1]=!0;_.oi(a.Fa)};
Xua=function(a){function b(m,p){if(!l[m]){var q=a.m>>2,r=12+(a.m>>1),t=document.createElement("div");_.zE(t);_.sm(t,"gm-bundled-control");10==m||11==m||12==m||6==m||9==m?_.sm(t,"gm-bundled-control-on-bottom"):_.yE(t,"gm-bundled-control-on-bottom");t.style.margin=_.Nl(q);_.Nm(t);l[m]=new cF(t,m,r);a.G.addElement(t,m,!1,.1)}m=l[m];m.add(p);a.na.push({Aa:p,Sl:m})}function c(m){return(a.get(m)||{}).position}a.K&&(Hua(a.K),a.K.unbindAll(),a.K=null);a.D&&(a.D.unbindAll(),a.D=null);a.ca&&(a.ca.unbindAll(),
a.ca=null);for(var d=_.A(a.na),e=d.next();!e.done;e=d.next())qva(a,e.value);a.na=[];d=a.Fb=kva(a);var f=a.kc=jva(a),g=a.Ya=LF(a),h=a.Mb=lva(a);a.Ab=mva(a);e=d&&(c("panControlOptions")||9);d=f&&(c("zoomControlOptions")||3==f&&6||9);var k=3==f||_.Qm();g=g&&(c("streetViewControlOptions")||9);h=h&&(c("rotateControlOptions")||k&&6||9);var l=a.Nd;d&&(f=sva(a,f),b(d,f));g&&(wva(a),b(g,a.Ra));e&&a.h&&_.qm().transform&&(f=tva(a),b(e,f));h&&(e=uva(a),b(h,e));a.X&&(a.X.remove(),a.X=null);if(e=ova(a)&&9)f=vva(a),
b(e,f);a.D&&a.K&&a.K.Yk&&h==d&&a.D.bindTo("mouseover",a.K.Yk);d=_.A(a.na);for(e=d.next();!e.done;e=d.next())_.M(e.value.Aa,"resize")};kva=function(a){var b=a.get("panControl"),c=MF(a);if(void 0!==b||c)return a.h||(_.P(a.W,b?"Cpy":"Cpn"),_.rg(a.W,b?148255:148254)),!!b;b=a.get("size");return _.Qm()||!b?!1:400<=b.width&&370<=b.height||!!a.h};mva=function(a){return a.h?!1:MF(a)?1==a.get("myLocationControl"):0!=a.get("myLocationControl")};
lva=function(a){var b=a.get("rotateControl"),c=MF(a);if(void 0!==b||c)_.P(a.W,b?"Cry":"Crn"),_.rg(a.W,b?148257:148256);return!a.get("size")||a.h?!1:c?1==b:0!=b};jva=function(a){var b=a.get("zoomControl"),c=MF(a);return 0==b||c&&void 0===b?(a.h||(_.P(a.W,"Czn"),_.rg(a.W,148262)),null):a.get("size")?1:null};OF=function(a){if(a.aa){var b=a.get("scaleControl");void 0!==b&&(_.P(a.W,b?"Csy":"Csn"),_.rg(a.W,b?148259:148258));b?(a=a.aa,a.j=!0,tF(a)):(a=a.aa,a.j=!1,tF(a))}};
cva=function(a){if(a.W){var b=_.Yq("Map Scale");_.Nm(b);_.Om(b);a.aa=new Bua(b,_.ZE(b,a.J),new _.vq([_.Br(a,"projection"),_.Br(a,"bottomRight"),_.Br(a,"zoom")],gta));OF(a)}};
wva=function(a){if(!a.H&&!a.ya&&a.wb&&a.W){var b=a.H=new HF(a.W,a.wb,a.Ra,a.J,a.Nb,_.hg,a.Ca,a.m,a.Eb,a.Ec||void 0);b.bindTo("mapHeading",a,"heading");b.bindTo("tilt",a);b.bindTo("projection",a.W);b.bindTo("mapTypeId",a);a.bindTo("panoramaVisible",b);b.bindTo("mapSize",a,"size");b.bindTo("display",a,"streetViewControl");b.bindTo("disableDefaultUI",a);xva(a)}};
xva=function(a){var b=a.H;if(b){var c=b.D,d=a.get("streetView");if(d!=c){if(c){var e=c.__gm;e.unbind("result");e.unbind("heading");c.unbind("passiveLogo");c.h.removeListener(a.dt,a);c.h.set(!1)}d&&(c=d.__gm,null!=c.get("result")&&b.set("result",c.get("result")),c.bindTo("isHover",b),c.bindTo("result",b),null!=c.get("heading")&&b.set("heading",c.get("heading")),c.bindTo("heading",b),d.bindTo("passiveLogo",a),d.h.addListener(a.dt,a),a.set("panoramaVisible",d.get("visible")),b.bindTo("client",d));b.D=
d}}};qva=function(a,b){b.Sl?(b.Sl.remove(b.Aa),delete b.Sl):a.G.xf(b.Aa)};
yva=function(a,b,c,d,e,f,g,h,k,l,m,p,q,r,t,u,w){var y=b.get("streetView");k=b.__gm;if(y&&k){p=new _.yD(_.Tu(),y.get("client"));y=_.ida[y.get("client")];var z=new KF({vv:function(R){return q.fromContainerPixelToLatLng(new _.Q(R.clientX,R.clientY))},Rq:b.controls,ur:l,Ol:m,Xr:a,map:b,Ax:b.mapTypes,Gg:d,Ss:!0,Ha:r,controlSize:b.get("controlSize")||40,Cz:y,ct:p,kx:t,qg:u,pg:w}),H=new _.hD(["bounds"],"bottomRight",function(R){return R&&_.dl(R)}),G,O;_.Rl(b,"idle",function(){var R=b.get("bounds");R!=G&&
(z.set("bounds",R),H.set("bounds",R),G=R);R=b.get("center");R!=O&&(z.set("center",R),O=R)});z.bindTo("bottomRight",H);z.bindTo("disableDefaultUI",b);z.bindTo("heading",b);z.bindTo("projection",b);z.bindTo("reportErrorControl",b);z.bindTo("passiveLogo",b);z.bindTo("zoom",k);z.bindTo("mapTypeId",c);z.bindTo("attributionText",e);z.bindTo("zoomRange",g);z.bindTo("aerialAvailableAtZoom",h);z.bindTo("tilt",h);z.bindTo("desiredTilt",h);z.bindTo("keyboardShortcuts",b,"keyboardShortcuts",!0);z.bindTo("mapTypeControlOptions",
b,null,!0);z.bindTo("panControlOptions",b,null,!0);z.bindTo("rotateControlOptions",b,null,!0);z.bindTo("scaleControlOptions",b,null,!0);z.bindTo("streetViewControlOptions",b,null,!0);z.bindTo("zoomControlOptions",b,null,!0);z.bindTo("mapTypeControl",b);z.bindTo("myLocationControlOptions",b);z.bindTo("fullscreenControlOptions",b,null,!0);b.get("fullscreenControlOptions")&&z.notify("fullscreenControlOptions");z.bindTo("panControl",b);z.bindTo("rotateControl",b);z.bindTo("motionTrackingControl",b);z.bindTo("motionTrackingControlOptions",
b,null,!0);z.bindTo("scaleControl",b);z.bindTo("streetViewControl",b);z.bindTo("fullscreenControl",b);z.bindTo("zoomControl",b);z.bindTo("myLocationControl",b);z.bindTo("rmiAvailable",f,"available");z.bindTo("streetView",b);z.bindTo("fontLoaded",k);z.bindTo("size",k);k.bindTo("renderHeading",z);_.Cf(z,"panbyfraction",k)}};
zva=function(a,b,c,d,e,f,g,h){var k=new _.yD(_.Tu(),g.get("client")),l=new KF({Rq:f,ur:d,Ol:h,Xr:e,Gg:c,controlSize:g.get("controlSize")||40,Ss:!1,Dz:g,ct:k});l.set("streetViewControl",!1);l.bindTo("attributionText",b,"copyright");l.set("mapTypeId","streetview");l.set("tilt",!0);l.bindTo("heading",b);l.bindTo("zoom",b,"zoomFinal");l.bindTo("zoomRange",b);l.bindTo("pov",b,"pov");l.bindTo("position",g);l.bindTo("pano",g);l.bindTo("passiveLogo",g);l.bindTo("floors",b);l.bindTo("floorId",b);l.bindTo("rmiWidth",
g);l.bindTo("fullscreenControlOptions",g,null,!0);l.bindTo("panControlOptions",g,null,!0);l.bindTo("zoomControlOptions",g,null,!0);l.bindTo("fullscreenControl",g);l.bindTo("panControl",g);l.bindTo("zoomControl",g);l.bindTo("disableDefaultUI",g);l.bindTo("fontLoaded",g.__gm);l.bindTo("size",b);a.view&&a.view.addListener("scene_changed",function(){var m=a.view.get("scene");l.set("isCustomPanorama","c"==m)});l.Fa.Xc();_.Cf(l,"panbyfraction",a)};
PF=function(a,b,c){this.T=a;this.N=b;this.K=c;this.m=this.j=0;this.C=null;this.H=this.h=0;this.F=this.J=null;_.Ql(a,"keydown",this,this.Gw);_.Ql(a,"keypress",this,this.sv);_.Ql(a,"keyup",this,this.Ty);this.D={};this.G={}};Ava=function(a){var b=a.get("zoom");_.he(b)&&a.set("zoom",b+1)};Bva=function(a){var b=a.get("zoom");_.he(b)&&a.set("zoom",b-1)};QF=function(a,b,c){_.M(a,"panbyfraction",b,c)};Cva=function(a,b){return!!(b.target!==a.T||b.ctrlKey||b.altKey||b.metaKey||0==a.get("enabled"))};
Eva=function(a,b,c,d,e){var f=new PF(b,d,e);f.bindTo("zoom",a);f.bindTo("enabled",a,"keyboardShortcuts");d&&f.bindTo("tilt",a.__gm);e&&f.bindTo("heading",a);(d||e)&&_.Cf(f,"tiltrotatebynow",a.__gm);_.Cf(f,"panbyfraction",a.__gm);_.Cf(f,"panbynow",a.__gm);_.Cf(f,"panby",a.__gm);Dva(a,b,d,e);var g=a.__gm.G,h;_.Rl(a,"streetview_changed",function(){var k=a.get("streetView"),l=h;l&&_.tf(l);h=null;k&&(h=_.Rl(k,"visible_changed",function(){k.getVisible()&&k===g?(b.blur(),c.style.visibility="hidden"):c.style.visibility=
""}))})};Dva=function(a,b,c,d){c=new _.xD({pg:d,qg:c,ownerElement:b,Tk:!1,Fi:"map"});var e=_.Ih();c.element.id=e;c.element.style.display="none";b.appendChild(c.element);_.Rl(a,"keyboardshortcuts_changed",function(){_.ol(a)?b.setAttribute("aria-describedby",e):b.removeAttribute("aria-describedby")})};RF=function(){this.Pp=FE;this.wx=yva;this.yx=zva;this.xx=Eva};pta={};var sta=_.xl(_.Wa(".dismissButton{background-color:#fff;border:1px solid #dadce0;color:#1a73e8;border-radius:4px;font-family:Roboto,sans-serif;font-size:14px;height:36px;cursor:pointer;padding:0 24px}.dismissButton:hover{background-color:rgba(66,133,244,.04);border:1px solid #d2e3fc}.dismissButton:focus{background-color:rgba(66,133,244,.12);border:1px solid #d2e3fc;outline:0}.dismissButton:focus:not(:focus-visible){background-color:#fff;border:1px solid #dadce0;outline:none}.dismissButton:focus-visible{background-color:rgba(66,133,244,.12);border:1px solid #d2e3fc;outline:0}.dismissButton:hover:focus{background-color:rgba(66,133,244,.16);border:1px solid #d2e2fd}.dismissButton:hover:focus:not(:focus-visible){background-color:rgba(66,133,244,.04);border:1px solid #d2e3fc}.dismissButton:hover:focus-visible{background-color:rgba(66,133,244,.16);border:1px solid #d2e2fd}.dismissButton:active{background-color:rgba(66,133,244,.16);border:1px solid #d2e2fd;box-shadow:0 1px 2px 0 rgba(60,64,67,.3),0 1px 3px 1px rgba(60,64,67,.15)}.dismissButton:disabled{background-color:#fff;border:1px solid #f1f3f4;color:#3c4043}\n"));var Fva=new _.x.Set([3,12,6,9]);_.B(FE,_.N);FE.prototype.Xa=function(){return _.Fi(this.j)};FE.prototype.addElement=function(a,b,c,d){var e=this;c=void 0===c?!1:c;var f=this.h.get(b);if(f){d=void 0!==d&&_.he(d)?d:f.length;var g;for(g=0;g<f.length&&!(f[g].index>d);++g);f.splice(g,0,{element:a,border:!!c,index:d,listener:_.L(a,"resize",function(){return _.oi(e.Fa)})});_.Jm(a);a.style.visibility="hidden";c=this.C.get(b);b=Fva.has(b)?f.length-g-1:g;c.insertBefore(a,c.children[b]);_.oi(this.Fa)}};
FE.prototype.xf=function(a){a.parentNode&&a.parentNode.removeChild(a);for(var b=_.A(_.v(this.h,"values").call(this.h)),c=b.next();!c.done;c=b.next()){c=c.value;for(var d=0;d<c.length;++d)if(c[d].element===a){var e=a;e.style.top="auto";e.style.bottom="auto";e.style.left="auto";e.style.right="auto";_.tf(c[d].listener);c.splice(d,1)}}_.oi(this.Fa)};
FE.prototype.m=function(){var a=this.Xa(),b=a.width;a=a.height;var c=this.h,d=[],e=IE(c.get(1),"left","top",d),f=JE(c.get(5),"left","top",d);d=[];var g=IE(c.get(10),"left","bottom",d),h=JE(c.get(6),"left","bottom",d);d=[];var k=IE(c.get(3),"right","top",d),l=JE(c.get(7),"right","top",d);d=[];var m=IE(c.get(12),"right","bottom",d);d=JE(c.get(9),"right","bottom",d);var p=vta(c.get(11),"bottom",b),q=vta(c.get(2),"top",b),r=KE(c.get(4),"left",b,a);KE(c.get(13),"center",b,a);c=KE(c.get(8),"right",b,a);
this.set("bounds",new _.pi([new _.Q(Math.max(r,e.width,g.width,f.width,h.width)||0,Math.max(q,e.height,f.height,k.height,l.height)||0),new _.Q(b-(Math.max(c,k.width,m.width,l.width,d.width)||0),a-(Math.max(p,g.height,m.height,h.height,d.height)||0))]))};_.Oa(LE,_.N);_.B(yta,_.N);_.B(ME,_.N);ME.prototype.card_changed=function(){var a=this.get("card");this.h&&this.j.removeChild(this.h);if(a){var b=this.h=_.Lm("div");b.style.backgroundColor="white";b.appendChild(a);b.style.margin=_.Nl(10);b.style.padding=_.Nl(1);_.rw(b,"0 1px 4px -1px rgba(0,0,0,0.3)");AE(b,_.Nl(2));this.j.appendChild(b);this.h=b}else this.h=null};ME.prototype.getDiv=function(){return this.j};var VE=_.xl(_.Wa(".gm-control-active>img{box-sizing:content-box;display:none;left:50%;pointer-events:none;position:absolute;top:50%;transform:translate(-50%,-50%)}.gm-control-active>img:nth-child(1){display:block}.gm-control-active:focus>img:nth-child(1),.gm-control-active:hover>img:nth-child(1),.gm-control-active:active>img:nth-child(1),.gm-control-active:disabled>img:nth-child(1){display:none}.gm-control-active:focus>img:nth-child(2),.gm-control-active:hover>img:nth-child(2){display:block}.gm-control-active:active>img:nth-child(3){display:block}.gm-control-active:disabled>img:nth-child(4){display:block}\n"));_.Oa(OE,_.Bz);OE.prototype.fill=function(a){_.zz(this,0,_.Ix(a))};var NE="t-avKK8hDgg9Q";_.B(PE,_.E);PE.prototype.getHeading=function(){return _.Od(this.o,1)};PE.prototype.setHeading=function(a){_.D(this.o,1,a)};var QE={},RE=null;_.Oa(TE,_.hi);TE.prototype.j=function(a){this.m(a)};_.Oa(UE,TE);UE.prototype.stop=function(a){SE(this);this.h=0;a&&(this.progress=1);Kta(this,this.progress);this.j("stop");this.j("end")};UE.prototype.Cb=function(){0==this.h||this.stop(!1);this.j("destroy");UE.Ge.Cb.call(this)};UE.prototype.j=function(a){this.m(new Lta(a,this))};_.Oa(Lta,_.Oh);_.B(WE,_.N);
WE.prototype.changed=function(){!this.m&&this.h&&(this.h.stop(),this.h=null);var a=this.get("pov");if(a){var b=new PE;b.setHeading(_.ee(-a.heading,0,360));_.Mk(_.I(b.o,3,_.ux),_.vx(_.sb(_.Zq["compass_background.svg"])));_.Mk(_.I(b.o,4,_.ux),_.vx(_.sb(_.Zq["compass_needle_normal.svg"])));_.Mk(_.I(b.o,5,_.ux),_.vx(_.sb(_.Zq["compass_needle_hover.svg"])));_.Mk(_.I(b.o,6,_.ux),_.vx(_.sb(_.Zq["compass_needle_active.svg"])));_.Mk(_.I(b.o,7,_.ux),_.vx(_.sb(_.Zq["compass_rotate_normal.svg"])));_.Mk(_.I(b.o,
8,_.ux),_.vx(_.sb(_.Zq["compass_rotate_hover.svg"])));_.Mk(_.I(b.o,9,_.ux),_.vx(_.sb(_.Zq["compass_rotate_active.svg"])));_.D(b.o,10,"\u041f\u043e\u0432\u0435\u0440\u043d\u0443\u0442\u0438 \u043f\u0440\u043e\u0442\u0438 \u0433\u043e\u0434\u0438\u043d\u043d\u0438\u043a\u043e\u0432\u043e\u0457 \u0441\u0442\u0440\u0456\u043b\u043a\u0438");_.D(b.o,11,"\u041f\u043e\u0432\u0435\u0440\u043d\u0443\u0442\u0438 \u0437\u0430 \u0433\u043e\u0434\u0438\u043d\u043d\u0438\u043a\u043e\u0432\u043e\u044e \u0441\u0442\u0440\u0456\u043b\u043a\u043e\u044e");
_.D(b.o,12,"\u0421\u043a\u0438\u043d\u0443\u0442\u0438");this.j.update([b])}};WE.prototype.mapSize_changed=function(){XE(this)};WE.prototype.disableDefaultUI_changed=function(){XE(this)};WE.prototype.panControl_changed=function(){XE(this)};_.B(Sta,_.N);var Qta=[{mw:-52,close:-78,top:-86,backgroundColor:"#fff"},{mw:0,close:-26,top:-86,backgroundColor:"#222"}];var Tta=_.xl(_.Wa(".gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span,.gm-style .gm-style-mtc div{font-size:10px;box-sizing:border-box}.gm-style .gm-style-cc a,.gm-style .gm-style-cc button,.gm-style .gm-style-cc span{outline-offset:3px}\n"));_.B(bF,_.N);_.n=bF.prototype;_.n.fontLoaded_changed=function(){var a=this;return _.Ca(function(b){aF(a);b.h=0})};_.n.keyboardShortcutsShown_changed=function(){aF(this)};_.n.zh=function(){this.get("keyboardShortcutsShown")&&(this.Ta.style.display="",this.h.textContent="",this.h.appendChild(this.D),_.Iw(),_.M(this,"update"))};
_.n.yh=function(){this.get("keyboardShortcutsShown")&&(this.Ta.style.display="",this.h.textContent="",this.h.textContent="\u041a\u043e\u043c\u0431\u0456\u043d\u0430\u0446\u0456\u0457 \u043a\u043b\u0430\u0432\u0456\u0448",_.Iw(),_.M(this,"update"))};_.n.bc=function(){this.get("keyboardShortcutsShown")||(this.Ta.style.display="none",_.M(this,"update"))};_.n.Td=function(){return this.Ta};_.B(Xta,_.N);cF.prototype.add=function(a){a.style.position="absolute";this.m?this.h.insertBefore(a,this.h.firstChild):this.h.appendChild(a);a=Yta(this,a);this.j.push(a);dF(this,a)};cF.prototype.remove=function(a){var b=this;this.h.removeChild(a);hta(this.j,function(c,d){c.element===a&&(b.j.splice(d,1),c&&(dF(b,c),c.Oo&&(_.tf(c.Oo),delete c.Oo)))})};_.gn("api-3/images/my_location_spinner",!0,!0);_.Oa(eF,_.N);
eF.prototype.changed=function(a){if("url"!=a)if(this.get("pano")){a=this.get("pov");var b=this.get("position");a&&b&&(a=_.Lra(a,b,this.get("pano"),this.h),this.set("url",a))}else{a={};if(b=this.get("center"))b=new _.Me(b.lat(),b.lng()),a.ll=b.toUrlValue();b=this.get("zoom");_.he(b)&&(a.z=b);b=this.get("mapTypeId");(b="terrain"==b?"p":"hybrid"==b?"h":_.Qs[b])&&(a.t=b);if(b=this.get("pano")){a.z=17;a.layer="c";var c=this.get("position");c&&(a.cbll=c.toUrlValue());a.panoid=b;(b=this.get("pov"))&&(a.cbp=
"12,"+b.heading+",,"+Math.max(b.zoom-3)+","+-b.pitch)}a.hl=_.Ld(_.Pd(_.hg));a.gl=_.Md(_.Pd(_.hg));a.mapclient=_.Bi[35]?"embed":"apiv3";var d=[];_.Zd(a,function(e,f){d.push(e+"="+f)});this.set("url",this.h+"?"+d.join("&"))}};fF.prototype.getDiv=function(){return this.m};_.B(cua,_.N);_.B(iF,_.N);iF.prototype.kb=function(){return this.h};var eua=_.xl(_.Wa(".ssQIHO-checkbox-menu-item>span>span{background-color:#000;display:inline-block}@media (forced-colors:active),(prefers-contrast:more){.ssQIHO-checkbox-menu-item>span>span{background-color:ButtonText}}\n"));_.B(kF,_.N);kF.prototype.kb=function(){return this.h};_.B(lF,_.N);lF.prototype.kb=function(){return this.h};_.Oa(gua,_.N);_.B(mF,_.N);mF.prototype.F=function(){var a=this.h;a.timeout&&(window.clearTimeout(a.timeout),a.timeout=null)};mF.prototype.active_changed=function(){this.F();if(this.get("active"))kua(this);else{var a=this.h;a.listeners&&(_.ib(a.listeners,_.tf),a.listeners=null);a.contains(document.activeElement)&&this.C.focus();this.j=null;_.nw(a)}};var oua=_.xl(_.Wa(".gm-style .gm-style-mtc label,.gm-style .gm-style-mtc div{font-weight:400}.gm-style .gm-style-mtc ul,.gm-style .gm-style-mtc li{box-sizing:border-box}\n"));_.B(nua,_.N);_.B(nF,_.N);nF.prototype.mapSize_changed=function(){qua(this)};nF.prototype.display_changed=function(){qua(this)};_.B(oF,_.N);oF.prototype.changed=function(a){if(!this.h)if("mapTypeId"==a){a=this.get("mapTypeId");var b=this.W[a];b&&b.mapTypeId&&(a=b.mapTypeId);pF(this,"internalMapTypeId",a);b&&b.Ck&&pF(this,b.Ck,b.value)}else rua(this)};_.B(qF,_.N);_.n=qF.prototype;
_.n.sessionState_changed=function(){var a=this.get("sessionState");if(a){var b=new _.pC;_.Mk(b,a);a=_.I(b.o,10,_.pA);_.D(a.o,1,1);_.D(b.o,12,!0);b=_.Jra(b,this.D);b+="&rapsrc=apiv3";this.h.setAttribute("href",b);this.C=b;this.get("available")&&this.set("rmiLinkData",{label:"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0443 \u043d\u0430 \u043a\u0430\u0440\u0442\u0456",tooltip:"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 Google \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0438 \u0432 \u043a\u0430\u0440\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0447\u043d\u0438\u0445 \u0434\u0430\u043d\u0438\u0445 \u0430\u0431\u043e \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u0456 \u0434\u043e\u0440\u0456\u0433",url:this.C})}};
_.n.available_changed=function(){rF(this)};_.n.enabled_changed=function(){rF(this)};_.n.mapTypeId_changed=function(){rF(this)};_.n.zh=function(){vua(this)&&(_.Iw(),_.P(this.W,"Rs"),_.rg(this.W,148263),this.j.style.display="",this.h.textContent="",this.h.appendChild(this.F))};_.n.yh=function(){vua(this)&&(_.Iw(),_.P(this.W,"Rs"),_.rg(this.W,148263),this.j.style.display="",this.h.textContent="\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u043e\u043c\u0438\u043b\u043a\u0443 \u043d\u0430 \u043a\u0430\u0440\u0442\u0456")};
_.n.bc=function(){this.j.style.display="none"};_.n.Td=function(){return this.j};_.B(sF,_.N);
sF.prototype.refresh=function(){var a=this.get("mapSize"),b=!!this.get("aerialAvailableAtZoom");a=!!this.get("rotateControl")||a&&200<=a.width&&200<=a.height;b=b&&a;a=this.J;wua(this.D,this.j,this.F);this.m.style.display=this.j?"block":"none";this.G.style.display=this.j?"block":"none";this.C.style.display=this.j?"block":"none";this.H.style.display=this.j?"block":"none";var c=this.F,d=Math.floor(3*this.F)+2;d=this.j?d:this.F;this.h.style.width=_.Nl(c);this.h.style.height=_.Nl(d);a.dataset.controlWidth=String(c);
a.dataset.controlHeight=String(d);_.mw(a,b);_.M(a,"resize")};_.B(zua,_.N);_.n=Bua.prototype;_.n.show=function(){this.j&&(this.Ta.style.display="")};_.n.bc=function(){this.j||(this.Ta.style.display="none")};_.n.zh=function(){this.show()};_.n.yh=function(){this.show()};_.n.Td=function(){return this.Ta};Eua.prototype.update=function(a){this.m=a;var b=_.A(this.h);for(var c=b.next();!c.done;c=b.next()){var d=c.value;d.bc();d.zh()}if(a<this.Ta.offsetWidth)for(d=_.A(this.j),c=d.next();!c.done;c=d.next())if(c=c.value,b=this.Ta.offsetWidth,a<b)c.bc();else break;else for(d=this.j.length-1;0<=d;d--)c=this.j[d],c.yh(),b=this.Ta.offsetWidth,a<b&&c.zh();_.M(this.Ta,"resize")};var vF={},Gva=vF[1]={};Gva.backgroundColor="#fff";Gva.Zq="#e6e6e6";var Hva=vF[2]={};Hva.backgroundColor="#222";Hva.Zq="#1a1a1a";_.B(wF,_.N);wF.prototype.changed=function(a){if("zoom"===a||"zoomRange"===a){a=this.get("zoom");var b=this.get("zoomRange");"number"===typeof a&&b&&(this.D.disabled=a>=b.max,this.D.style.cursor=a>=b.max?"default":"pointer",this.F.disabled=a<=b.min,this.F.style.cursor=a<=b.min?"default":"pointer")}};_.B(xF,_.N);xF.prototype.getDiv=function(){return this.h};_.B(zF,_.N);_.n=zF.prototype;_.n.fontLoaded_changed=function(){yF(this)};_.n.attributionText_changed=function(){yF(this)};_.n.hidden_changed=function(){yF(this)};_.n.mapTypeId_changed=function(){"streetview"===this.get("mapTypeId")&&($E(this.D),this.m.style.color="#fff")};_.n.zh=function(){this.get("hidden")||(this.h.style.display="",this.m.style.display="",this.j.style.display="none",_.Iw())};
_.n.yh=function(){this.get("hidden")||(this.h.style.display="",this.m.style.display="none",this.j.style.display="",_.Iw())};_.n.bc=function(){this.get("hidden")&&(this.h.style.display="none")};_.n.Td=function(){return this.h};_.B(AF,_.N);AF.prototype.kb=function(){return this.h.element};AF.prototype.visible_changed=function(){this.get("visible")?(_.Iw(),this.m.appendChild(this.h.element),this.h.show()):this.h.bc()};AF.prototype.attributionText_changed=function(){var a=this.get("attributionText")||"";(this.j.textContent=a)||this.h.bc()};_.B(BF,_.N);_.n=BF.prototype;_.n.attributionText_changed=function(){var a=this.get("attributionText")||"";this.j.textContent=a};_.n.hidden_changed=function(){var a=!this.get("hidden");_.mw(this.h,a);a&&_.Iw()};_.n.zh=function(){};_.n.yh=function(){};_.n.bc=function(){};_.n.Td=function(){return this.h};_.B(CF,_.N);_.n=CF.prototype;_.n.hidden_changed=function(){_.M(this.h,"resize")};_.n.mapTypeId_changed=function(){"streetview"==this.get("mapTypeId")&&($E(this.h),this.m.style.color="#fff")};_.n.fontLoaded_changed=function(){_.M(this.h,"resize")};_.n.zh=function(){this.yh()};_.n.yh=function(){this.get("hidden")||(this.h.style.display="",_.Iw())};_.n.bc=function(){this.get("hidden")&&(this.h.style.display="none")};_.n.Td=function(){return this.h};_.B(Iua,_.N);_.Oa(DF,_.N);
DF.prototype.changed=function(a){if("sessionState"!=a){a=new _.pC;var b=this.get("zoom"),c=this.get("center"),d=this.get("pano");if(null!=b&&null!=c||null!=d){var e=this.h,f=_.I(a.o,2,_.lA),g=_.Ld(e);_.D(f.o,1,g);f=_.I(a.o,2,_.lA);e=_.Md(e);_.D(f.o,2,e);e=_.qC(a);f=this.get("mapTypeId");"hybrid"==f||"satellite"==f?_.D(e.o,1,3):(_.D(e.o,1,0),"terrain"==f&&(f=_.I(a.o,5,_.jA),_.ud(f.o,1,4)));f=_.I(e.o,2,_.rA);_.D(f.o,1,2);c&&(g=c.lng(),_.D(f.o,2,g),c=c.lat(),_.D(f.o,3,c));"number"===typeof b&&_.D(f.o,
6,b);f.setHeading(this.get("heading")||0);d&&(b=_.I(e.o,3,_.vA),_.D(b.o,1,d));this.set("sessionState",a)}else this.set("sessionState",null)}};_.B(EF,_.N);
EF.prototype.floors_changed=function(){var a=this.get("floorId"),b=this.get("floors"),c=this.m;if(1<_.Yd(b)){_.ow(c);_.ib(this.j,function(g){_.Wm(g)});this.j=[];for(var d=b.length,e=d-1;0<=e;--e){var f=_.Yq(b[e].description||b[e].Rp||"\u041f\u043e\u0432\u0435\u0440\u0445");b[e].Jn==a?(f.style.color="#aaa",f.style.fontWeight="bold",f.style.backgroundColor="#333"):(Jua(this,f,b[e].Dy),f.style.color="#999",f.style.fontWeight="400",f.style.backgroundColor="#222");f.style.height=f.style.width=_.Nl(this.h);
e==d-1?kta(f,_.Nl(_.Ez(this.h))):0==e&&lta(f,_.Nl(_.Ez(this.h)));_.Hm(b[e].Rp,f);c.appendChild(f);this.j.push(f)}setTimeout(function(){_.M(c,"resize")})}else _.nw(c)};_.B(FF,_.N);FF.prototype.F=function(){1==this.get("mode")&&this.set("mode",2)};FF.prototype.G=function(){2==this.get("mode")&&this.set("mode",1)};var Iva=[_.Zq["lilypad_0.svg"],_.Zq["lilypad_1.svg"],_.Zq["lilypad_2.svg"],_.Zq["lilypad_3.svg"],_.Zq["lilypad_4.svg"],_.Zq["lilypad_5.svg"],_.Zq["lilypad_6.svg"],_.Zq["lilypad_7.svg"],_.Zq["lilypad_8.svg"],_.Zq["lilypad_9.svg"],_.Zq["lilypad_10.svg"],_.Zq["lilypad_11.svg"],_.Zq["lilypad_12.svg"],_.Zq["lilypad_13.svg"],_.Zq["lilypad_14.svg"],_.Zq["lilypad_15.svg"]],Oua=[_.Zq["lilypad_pegman_0.svg"],_.Zq["lilypad_pegman_1.svg"],_.Zq["lilypad_pegman_2.svg"],_.Zq["lilypad_pegman_3.svg"],_.Zq["lilypad_pegman_4.svg"],
_.Zq["lilypad_pegman_5.svg"],_.Zq["lilypad_pegman_6.svg"],_.Zq["lilypad_pegman_7.svg"],_.Zq["lilypad_pegman_8.svg"],_.Zq["lilypad_pegman_9.svg"],_.Zq["lilypad_pegman_10.svg"],_.Zq["lilypad_pegman_11.svg"],_.Zq["lilypad_pegman_12.svg"],_.Zq["lilypad_pegman_13.svg"],_.Zq["lilypad_pegman_14.svg"],_.Zq["lilypad_pegman_15.svg"]];_.B(GF,_.N);_.n=GF.prototype;_.n.mode_changed=function(){Pua(this);Qua(this)};_.n.heading_changed=function(){7==this.j()&&Pua(this)};
_.n.position_changed=function(){var a=this.j();if(5==a||6==a||3==a||4==a)if(this.get("position")){this.J.setVisible(!0);this.K.setVisible(!1);a=this.set;var b=Nua(this);this.F!=b&&(this.F=b,this.D={url:Iva[b],scaledSize:new _.Eg(49,52),anchor:new _.Q(25,35)});a.call(this,"lilypadIcon",this.D)}else a=this.j(),5==a?this.h(6):3==a&&this.h(4);else(b=this.get("position"))&&1==a&&this.h(7),this.set("dragPosition",b)};_.n.Zt=function(a){this.set("dragging",!0);this.h(5);this.C=a.pixel.x};
_.n.au=function(a){var b=this;a=a.pixel.x;a>b.C+5?(this.h(5),b.C=a):a<b.C-5&&(this.h(3),b.C=a);Qua(this);window.clearTimeout(b.m);b.m=window.setTimeout(function(){_.M(b,"hover");b.m=0},300)};_.n.Yt=function(){this.set("dragging",!1);this.h(1);window.clearTimeout(this.m);this.m=0};_.Oa(HF,_.N);_.n=HF.prototype;_.n.mode_changed=function(){var a=_.iD(this.bu());a!=this.m&&(a?Uua(this):Tua(this))};_.n.tilt_changed=HF.prototype.heading_changed=function(){this.m&&(Tua(this),Uua(this))};
_.n.ns=function(a){var b=this,c=this.get("dragPosition"),d=this.W.getZoom(),e=Math.max(50,35*Math.pow(2,16-d));this.set("hover",a);this.C=!1;_.gf("streetview").then(function(f){var g=b.G||void 0;b.j||(b.j=new f.tu(g),b.bindTo("sloTrackingId",b.j,"sloTrackingId",!0),b.bindTo("isHover",b.j,"isHover",!0),b.j.bindTo("result",b,null,!0));b.j.getPanoramaByLocation(c,e,g?void 0:100>e?"nearest":"best",a)})};
_.n.result_changed=function(){var a=this.get("result"),b=a&&a.location;this.set("position",b&&b.latLng);this.set("description",b&&b.shortDescription);this.set("panoId",b&&b.pano);this.C?this.jn(1):this.get("hover")||this.set("panoramaVisible",!!a)};_.n.panoramaVisible_changed=function(){this.C=0==this.get("panoramaVisible");var a=this.get("panoramaVisible"),b=this.get("hover");a||b||this.jn(1);a&&this.notify("position")};_.n.bu=_.cg("mode");_.n.jn=_.dg("mode");_.Oa(JF,_.N);_.n=JF.prototype;_.n.visible_changed=function(){var a=!1!==this.get("visible");_.mw(this.Ta,a);_.M(this.Ta,"resize")};
_.n.takeDownUrl_changed=JF.prototype.pov_changed=JF.prototype.pano_changed=function(){var a=this.get("pov"),b=this.get("pano"),c=this.get("takeDownUrl");a&&(c||b)&&(a="1,"+parseFloat(a.heading.toFixed(3))+",,"+parseFloat(Math.max(0,a.zoom-1||0).toFixed(3))+","+parseFloat((-a.pitch).toFixed(3)),b=c?c+("&cbp="+a+"&hl="+_.Ld(_.Pd(_.hg))):this.Ej.getUrl("report",["panoid="+b,"cbp="+a,"hl="+_.Ld(_.Pd(_.hg))]),this.h.setAttribute("href",b),this.set("rmiLinkData",{label:(IF(),"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0438\u0442\u0438 \u043f\u0440\u043e \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0443"),
tooltip:"\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u0442\u0435 Google \u043f\u0440\u043e \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0443 \u0456\u0437 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f\u043c \u0443 \u0440\u0435\u0436\u0438\u043c\u0456 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0443 \u0432\u0443\u043b\u0438\u0446\u044c",url:b}))};_.n.zh=function(){};_.n.yh=function(){};_.n.bc=function(){};_.n.Td=function(){return this.Ta};_.B(KF,_.N);_.n=KF.prototype;_.n.disableDefaultUI_changed=function(){nva(this)};_.n.size_changed=function(){nva(this);this.get("size")&&this.ne.update(this.get("size").width)};_.n.mapTypeId_changed=function(){LF(this)!=this.Ya&&(this.F[1]=!0,_.oi(this.Fa));this.X&&this.X.setMapTypeId(this.get("mapTypeId"))};_.n.mapTypeControl_changed=function(){this.F[0]=!0;_.oi(this.Fa)};_.n.mapTypeControlOptions_changed=function(){this.F[0]=!0;_.oi(this.Fa)};
_.n.fullscreenControlOptions_changed=function(){this.F[3]=!0;_.oi(this.Fa)};_.n.scaleControl_changed=function(){OF(this)};_.n.scaleControlOptions_changed=function(){OF(this)};_.n.keyboardShortcuts_changed=function(){var a=!!(this.W&&_.ol(this.W)||this.h);a?(this.ea.Ta.style.display="",this.C.set("keyboardShortcutsShown",!0)):a||(this.ea.Ta.style.display="none",this.C.set("keyboardShortcutsShown",!1))};_.n.panControl_changed=function(){NF(this)};_.n.panControlOptions_changed=function(){NF(this)};
_.n.rotateControl_changed=function(){NF(this)};_.n.rotateControlOptions_changed=function(){NF(this)};_.n.streetViewControl_changed=function(){NF(this)};_.n.streetViewControlOptions_changed=function(){NF(this)};_.n.zoomControl_changed=function(){NF(this)};_.n.zoomControlOptions_changed=function(){NF(this)};_.n.myLocationControl_changed=function(){NF(this)};_.n.myLocationControlOptions_changed=function(){NF(this)};_.n.streetView_changed=function(){xva(this)};
_.n.dt=function(a){this.get("panoramaVisible")!=a&&this.set("panoramaVisible",a)};_.n.panoramaVisible_changed=function(){var a=this.get("streetView");a&&(this.H&&a.__gm.bindTo("sloTrackingId",this.H),a.h.set(!!this.get("panoramaVisible")))};var Jva=[37,38,39,40],Kva=[38,40],Lva=[37,39],Mva={38:[0,-1],40:[0,1],37:[-1,0],39:[1,0]},Nva={38:[0,1],40:[0,-1],37:[-1,0],39:[1,0]};var SF=Object.freeze([].concat(_.ma(Kva),_.ma(Lva)));_.B(PF,_.N);_.n=PF.prototype;
_.n.Gw=function(a){if(Cva(this,a))return!0;var b=!1;switch(a.keyCode){case 38:case 40:case 37:case 39:b=a.shiftKey&&0<=Lva.indexOf(a.keyCode)&&this.K&&!this.j;a.shiftKey&&0<=Kva.indexOf(a.keyCode)&&this.N&&!this.j||b?(this.G[a.keyCode]=!0,this.m||(this.H=0,this.h=1,this.cr())):this.m||(this.D[a.keyCode]=1,this.j||(this.C=new _.jD(100),this.br()));b=!0;break;case 34:QF(this,0,.75);b=!0;break;case 33:QF(this,0,-.75);b=!0;break;case 36:QF(this,-.75,0);b=!0;break;case 35:QF(this,.75,0);b=!0;break;case 187:case 107:Ava(this);
b=!0;break;case 189:case 109:Bva(this),b=!0}switch(a.which){case 61:case 43:Ava(this);b=!0;break;case 45:case 95:case 173:Bva(this),b=!0}b&&(_.lf(a),_.mf(a));return!b};_.n.sv=function(a){if(Cva(this,a))return!0;switch(a.keyCode){case 38:case 40:case 37:case 39:case 34:case 33:case 36:case 35:case 187:case 107:case 189:case 109:return _.lf(a),_.mf(a),!1}switch(a.which){case 61:case 43:case 45:case 95:case 173:return _.lf(a),_.mf(a),!1}return!0};
_.n.Ty=function(a){var b=!1;switch(a.keyCode){case 38:case 40:case 37:case 39:this.D[a.keyCode]=null,this.G[a.keyCode]=!1,b=!0}return!b};_.n.br=function(){for(var a=0,b=0,c=!1,d=_.A(Jva),e=d.next();!e.done;e=d.next())e=e.value,this.D[e]&&(e=_.A(Mva[e]),c=e.next().value,e=e.next().value,a+=c,b+=e,c=!0);c?(c=1,_.kD(this.C)&&(c=this.C.next()),d=Math.round(35*c*a),c=Math.round(35*c*b),0===d&&(d=a),0===c&&(c=b),_.M(this,"panbynow",d,c,1),this.j=_.hw(this,this.br,10)):this.j=0};
_.n.cr=function(){for(var a=0,b=0,c=!1,d=0;d<SF.length;d++)this.G[SF[d]]&&(c=Nva[SF[d]],a+=c[0],b+=c[1],c=!0);c?(_.M(this,"tiltrotatebynow",this.h*a,this.h*b),this.m=_.hw(this,this.cr,10),this.h=Math.min(1.8,this.h+.01),this.H++,this.J={x:a,y:b}):(this.m=0,this.F=new _.jD(Math.min(Math.round(this.H/2),35),1),_.hw(this,this.dr,10))};_.n.dr=function(){if(!this.m&&!this.j&&_.kD(this.F)){var a=this.J,b=a.x;a=a.y;var c=this.F.next();_.M(this,"tiltrotatebynow",this.h*c*b,this.h*c*a);_.hw(this,this.dr,10)}};RF.prototype.Rs=function(a,b){a=_.tta(a,b).style;a.border="1px solid rgba(0,0,0,0.12)";a.borderRadius="5px";a.left="50%";a.maxWidth="375px";a.msTransform="translateX(-50%)";a.position="absolute";a.transform="translateX(-50%)";a.width="calc(100% - 10px)";a.zIndex="1"};RF.prototype.cp=function(a){if(_.gda()&&!a.__gm_bbsp){a.__gm_bbsp=!0;var b=new _.ym("https://developers.google.com/maps/documentation/javascript/error-messages#unsupported-browsers");new Zta(a,b)}};_.hf("controls",new RF);});
